/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"fmt"
)

// checks if the ColumnProfileDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ColumnProfileDto{}

// ColumnProfileDto struct for ColumnProfileDto
type ColumnProfileDto struct {
	Name string `json:"name"`
	DataType string `json:"dataType"`
	RowCount int64 `json:"rowCount"`
	NullCount int64 `json:"nullCount"`
	Minimum NullableString `json:"minimum"`
	Maximum NullableString `json:"maximum"`
	ApproxDistinct NullableString `json:"approxDistinct"`
	Mean NullableString `json:"mean"`
	StandardDeviation NullableString `json:"standardDeviation"`
	FirstQuartile NullableString `json:"firstQuartile"`
	Median NullableString `json:"median"`
	ThirdQuartile NullableString `json:"thirdQuartile"`
	AdditionalProperties map[string]interface{}
}

type _ColumnProfileDto ColumnProfileDto

// NewColumnProfileDto instantiates a new ColumnProfileDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewColumnProfileDto(name string, dataType string, rowCount int64, nullCount int64, minimum NullableString, maximum NullableString, approxDistinct NullableString, mean NullableString, standardDeviation NullableString, firstQuartile NullableString, median NullableString, thirdQuartile NullableString) *ColumnProfileDto {
	this := ColumnProfileDto{}
	this.Name = name
	this.DataType = dataType
	this.RowCount = rowCount
	this.NullCount = nullCount
	this.Minimum = minimum
	this.Maximum = maximum
	this.ApproxDistinct = approxDistinct
	this.Mean = mean
	this.StandardDeviation = standardDeviation
	this.FirstQuartile = firstQuartile
	this.Median = median
	this.ThirdQuartile = thirdQuartile
	return &this
}

// NewColumnProfileDtoWithDefaults instantiates a new ColumnProfileDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewColumnProfileDtoWithDefaults() *ColumnProfileDto {
	this := ColumnProfileDto{}
	return &this
}

// GetName returns the Name field value
func (o *ColumnProfileDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ColumnProfileDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ColumnProfileDto) SetName(v string) {
	o.Name = v
}

// GetDataType returns the DataType field value
func (o *ColumnProfileDto) GetDataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value
// and a boolean to check if the value has been set.
func (o *ColumnProfileDto) GetDataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataType, true
}

// SetDataType sets field value
func (o *ColumnProfileDto) SetDataType(v string) {
	o.DataType = v
}

// GetRowCount returns the RowCount field value
func (o *ColumnProfileDto) GetRowCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value
// and a boolean to check if the value has been set.
func (o *ColumnProfileDto) GetRowCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowCount, true
}

// SetRowCount sets field value
func (o *ColumnProfileDto) SetRowCount(v int64) {
	o.RowCount = v
}

// GetNullCount returns the NullCount field value
func (o *ColumnProfileDto) GetNullCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NullCount
}

// GetNullCountOk returns a tuple with the NullCount field value
// and a boolean to check if the value has been set.
func (o *ColumnProfileDto) GetNullCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NullCount, true
}

// SetNullCount sets field value
func (o *ColumnProfileDto) SetNullCount(v int64) {
	o.NullCount = v
}

// GetMinimum returns the Minimum field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ColumnProfileDto) GetMinimum() string {
	if o == nil || o.Minimum.Get() == nil {
		var ret string
		return ret
	}

	return *o.Minimum.Get()
}

// GetMinimumOk returns a tuple with the Minimum field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnProfileDto) GetMinimumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Minimum.Get(), o.Minimum.IsSet()
}

// SetMinimum sets field value
func (o *ColumnProfileDto) SetMinimum(v string) {
	o.Minimum.Set(&v)
}

// GetMaximum returns the Maximum field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ColumnProfileDto) GetMaximum() string {
	if o == nil || o.Maximum.Get() == nil {
		var ret string
		return ret
	}

	return *o.Maximum.Get()
}

// GetMaximumOk returns a tuple with the Maximum field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnProfileDto) GetMaximumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Maximum.Get(), o.Maximum.IsSet()
}

// SetMaximum sets field value
func (o *ColumnProfileDto) SetMaximum(v string) {
	o.Maximum.Set(&v)
}

// GetApproxDistinct returns the ApproxDistinct field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ColumnProfileDto) GetApproxDistinct() string {
	if o == nil || o.ApproxDistinct.Get() == nil {
		var ret string
		return ret
	}

	return *o.ApproxDistinct.Get()
}

// GetApproxDistinctOk returns a tuple with the ApproxDistinct field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnProfileDto) GetApproxDistinctOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApproxDistinct.Get(), o.ApproxDistinct.IsSet()
}

// SetApproxDistinct sets field value
func (o *ColumnProfileDto) SetApproxDistinct(v string) {
	o.ApproxDistinct.Set(&v)
}

// GetMean returns the Mean field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ColumnProfileDto) GetMean() string {
	if o == nil || o.Mean.Get() == nil {
		var ret string
		return ret
	}

	return *o.Mean.Get()
}

// GetMeanOk returns a tuple with the Mean field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnProfileDto) GetMeanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mean.Get(), o.Mean.IsSet()
}

// SetMean sets field value
func (o *ColumnProfileDto) SetMean(v string) {
	o.Mean.Set(&v)
}

// GetStandardDeviation returns the StandardDeviation field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ColumnProfileDto) GetStandardDeviation() string {
	if o == nil || o.StandardDeviation.Get() == nil {
		var ret string
		return ret
	}

	return *o.StandardDeviation.Get()
}

// GetStandardDeviationOk returns a tuple with the StandardDeviation field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnProfileDto) GetStandardDeviationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StandardDeviation.Get(), o.StandardDeviation.IsSet()
}

// SetStandardDeviation sets field value
func (o *ColumnProfileDto) SetStandardDeviation(v string) {
	o.StandardDeviation.Set(&v)
}

// GetFirstQuartile returns the FirstQuartile field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ColumnProfileDto) GetFirstQuartile() string {
	if o == nil || o.FirstQuartile.Get() == nil {
		var ret string
		return ret
	}

	return *o.FirstQuartile.Get()
}

// GetFirstQuartileOk returns a tuple with the FirstQuartile field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnProfileDto) GetFirstQuartileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstQuartile.Get(), o.FirstQuartile.IsSet()
}

// SetFirstQuartile sets field value
func (o *ColumnProfileDto) SetFirstQuartile(v string) {
	o.FirstQuartile.Set(&v)
}

// GetMedian returns the Median field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ColumnProfileDto) GetMedian() string {
	if o == nil || o.Median.Get() == nil {
		var ret string
		return ret
	}

	return *o.Median.Get()
}

// GetMedianOk returns a tuple with the Median field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnProfileDto) GetMedianOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Median.Get(), o.Median.IsSet()
}

// SetMedian sets field value
func (o *ColumnProfileDto) SetMedian(v string) {
	o.Median.Set(&v)
}

// GetThirdQuartile returns the ThirdQuartile field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ColumnProfileDto) GetThirdQuartile() string {
	if o == nil || o.ThirdQuartile.Get() == nil {
		var ret string
		return ret
	}

	return *o.ThirdQuartile.Get()
}

// GetThirdQuartileOk returns a tuple with the ThirdQuartile field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnProfileDto) GetThirdQuartileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ThirdQuartile.Get(), o.ThirdQuartile.IsSet()
}

// SetThirdQuartile sets field value
func (o *ColumnProfileDto) SetThirdQuartile(v string) {
	o.ThirdQuartile.Set(&v)
}

func (o ColumnProfileDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ColumnProfileDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["dataType"] = o.DataType
	toSerialize["rowCount"] = o.RowCount
	toSerialize["nullCount"] = o.NullCount
	toSerialize["minimum"] = o.Minimum.Get()
	toSerialize["maximum"] = o.Maximum.Get()
	toSerialize["approxDistinct"] = o.ApproxDistinct.Get()
	toSerialize["mean"] = o.Mean.Get()
	toSerialize["standardDeviation"] = o.StandardDeviation.Get()
	toSerialize["firstQuartile"] = o.FirstQuartile.Get()
	toSerialize["median"] = o.Median.Get()
	toSerialize["thirdQuartile"] = o.ThirdQuartile.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ColumnProfileDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"dataType",
		"rowCount",
		"nullCount",
		"minimum",
		"maximum",
		"approxDistinct",
		"mean",
		"standardDeviation",
		"firstQuartile",
		"median",
		"thirdQuartile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varColumnProfileDto := _ColumnProfileDto{}

	err = json.Unmarshal(data, &varColumnProfileDto)

	if err != nil {
		return err
	}

	*o = ColumnProfileDto(varColumnProfileDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "dataType")
		delete(additionalProperties, "rowCount")
		delete(additionalProperties, "nullCount")
		delete(additionalProperties, "minimum")
		delete(additionalProperties, "maximum")
		delete(additionalProperties, "approxDistinct")
		delete(additionalProperties, "mean")
		delete(additionalProperties, "standardDeviation")
		delete(additionalProperties, "firstQuartile")
		delete(additionalProperties, "median")
		delete(additionalProperties, "thirdQuartile")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableColumnProfileDto struct {
	value *ColumnProfileDto
	isSet bool
}

func (v NullableColumnProfileDto) Get() *ColumnProfileDto {
	return v.value
}

func (v *NullableColumnProfileDto) Set(val *ColumnProfileDto) {
	v.value = val
	v.isSet = true
}

func (v NullableColumnProfileDto) IsSet() bool {
	return v.isSet
}

func (v *NullableColumnProfileDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColumnProfileDto(val *ColumnProfileDto) *NullableColumnProfileDto {
	return &NullableColumnProfileDto{value: val, isSet: true}
}

func (v NullableColumnProfileDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColumnProfileDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


