/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
)

// checks if the ExecuteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteRequest{}

// ExecuteRequest struct for ExecuteRequest
type ExecuteRequest struct {
	Sql NullableString `json:"sql,omitempty"`
	Language NullableString `json:"language,omitempty"`
	Source NullableString `json:"source,omitempty"`
	EffectiveLanguage NullableString `json:"effectiveLanguage,omitempty"`
	EffectiveSource NullableString `json:"effectiveSource,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ExecuteRequest ExecuteRequest

// NewExecuteRequest instantiates a new ExecuteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteRequest() *ExecuteRequest {
	this := ExecuteRequest{}
	return &this
}

// NewExecuteRequestWithDefaults instantiates a new ExecuteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteRequestWithDefaults() *ExecuteRequest {
	this := ExecuteRequest{}
	return &this
}

// GetSql returns the Sql field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecuteRequest) GetSql() string {
	if o == nil || IsNil(o.Sql.Get()) {
		var ret string
		return ret
	}
	return *o.Sql.Get()
}

// GetSqlOk returns a tuple with the Sql field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecuteRequest) GetSqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sql.Get(), o.Sql.IsSet()
}

// HasSql returns a boolean if a field has been set.
func (o *ExecuteRequest) HasSql() bool {
	if o != nil && o.Sql.IsSet() {
		return true
	}

	return false
}

// SetSql gets a reference to the given NullableString and assigns it to the Sql field.
func (o *ExecuteRequest) SetSql(v string) {
	o.Sql.Set(&v)
}
// SetSqlNil sets the value for Sql to be an explicit nil
func (o *ExecuteRequest) SetSqlNil() {
	o.Sql.Set(nil)
}

// UnsetSql ensures that no value is present for Sql, not even an explicit nil
func (o *ExecuteRequest) UnsetSql() {
	o.Sql.Unset()
}

// GetLanguage returns the Language field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecuteRequest) GetLanguage() string {
	if o == nil || IsNil(o.Language.Get()) {
		var ret string
		return ret
	}
	return *o.Language.Get()
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecuteRequest) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Language.Get(), o.Language.IsSet()
}

// HasLanguage returns a boolean if a field has been set.
func (o *ExecuteRequest) HasLanguage() bool {
	if o != nil && o.Language.IsSet() {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given NullableString and assigns it to the Language field.
func (o *ExecuteRequest) SetLanguage(v string) {
	o.Language.Set(&v)
}
// SetLanguageNil sets the value for Language to be an explicit nil
func (o *ExecuteRequest) SetLanguageNil() {
	o.Language.Set(nil)
}

// UnsetLanguage ensures that no value is present for Language, not even an explicit nil
func (o *ExecuteRequest) UnsetLanguage() {
	o.Language.Unset()
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecuteRequest) GetSource() string {
	if o == nil || IsNil(o.Source.Get()) {
		var ret string
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecuteRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *ExecuteRequest) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableString and assigns it to the Source field.
func (o *ExecuteRequest) SetSource(v string) {
	o.Source.Set(&v)
}
// SetSourceNil sets the value for Source to be an explicit nil
func (o *ExecuteRequest) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *ExecuteRequest) UnsetSource() {
	o.Source.Unset()
}

// GetEffectiveLanguage returns the EffectiveLanguage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecuteRequest) GetEffectiveLanguage() string {
	if o == nil || IsNil(o.EffectiveLanguage.Get()) {
		var ret string
		return ret
	}
	return *o.EffectiveLanguage.Get()
}

// GetEffectiveLanguageOk returns a tuple with the EffectiveLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecuteRequest) GetEffectiveLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EffectiveLanguage.Get(), o.EffectiveLanguage.IsSet()
}

// HasEffectiveLanguage returns a boolean if a field has been set.
func (o *ExecuteRequest) HasEffectiveLanguage() bool {
	if o != nil && o.EffectiveLanguage.IsSet() {
		return true
	}

	return false
}

// SetEffectiveLanguage gets a reference to the given NullableString and assigns it to the EffectiveLanguage field.
func (o *ExecuteRequest) SetEffectiveLanguage(v string) {
	o.EffectiveLanguage.Set(&v)
}
// SetEffectiveLanguageNil sets the value for EffectiveLanguage to be an explicit nil
func (o *ExecuteRequest) SetEffectiveLanguageNil() {
	o.EffectiveLanguage.Set(nil)
}

// UnsetEffectiveLanguage ensures that no value is present for EffectiveLanguage, not even an explicit nil
func (o *ExecuteRequest) UnsetEffectiveLanguage() {
	o.EffectiveLanguage.Unset()
}

// GetEffectiveSource returns the EffectiveSource field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecuteRequest) GetEffectiveSource() string {
	if o == nil || IsNil(o.EffectiveSource.Get()) {
		var ret string
		return ret
	}
	return *o.EffectiveSource.Get()
}

// GetEffectiveSourceOk returns a tuple with the EffectiveSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecuteRequest) GetEffectiveSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EffectiveSource.Get(), o.EffectiveSource.IsSet()
}

// HasEffectiveSource returns a boolean if a field has been set.
func (o *ExecuteRequest) HasEffectiveSource() bool {
	if o != nil && o.EffectiveSource.IsSet() {
		return true
	}

	return false
}

// SetEffectiveSource gets a reference to the given NullableString and assigns it to the EffectiveSource field.
func (o *ExecuteRequest) SetEffectiveSource(v string) {
	o.EffectiveSource.Set(&v)
}
// SetEffectiveSourceNil sets the value for EffectiveSource to be an explicit nil
func (o *ExecuteRequest) SetEffectiveSourceNil() {
	o.EffectiveSource.Set(nil)
}

// UnsetEffectiveSource ensures that no value is present for EffectiveSource, not even an explicit nil
func (o *ExecuteRequest) UnsetEffectiveSource() {
	o.EffectiveSource.Unset()
}

func (o ExecuteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Sql.IsSet() {
		toSerialize["sql"] = o.Sql.Get()
	}
	if o.Language.IsSet() {
		toSerialize["language"] = o.Language.Get()
	}
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}
	if o.EffectiveLanguage.IsSet() {
		toSerialize["effectiveLanguage"] = o.EffectiveLanguage.Get()
	}
	if o.EffectiveSource.IsSet() {
		toSerialize["effectiveSource"] = o.EffectiveSource.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExecuteRequest) UnmarshalJSON(data []byte) (err error) {
	varExecuteRequest := _ExecuteRequest{}

	err = json.Unmarshal(data, &varExecuteRequest)

	if err != nil {
		return err
	}

	*o = ExecuteRequest(varExecuteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sql")
		delete(additionalProperties, "language")
		delete(additionalProperties, "source")
		delete(additionalProperties, "effectiveLanguage")
		delete(additionalProperties, "effectiveSource")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExecuteRequest struct {
	value *ExecuteRequest
	isSet bool
}

func (v NullableExecuteRequest) Get() *ExecuteRequest {
	return v.value
}

func (v *NullableExecuteRequest) Set(val *ExecuteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteRequest(val *ExecuteRequest) *NullableExecuteRequest {
	return &NullableExecuteRequest{value: val, isSet: true}
}

func (v NullableExecuteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


