/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"fmt"
)

// checks if the DataConnectorFieldMappingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataConnectorFieldMappingRequest{}

// DataConnectorFieldMappingRequest struct for DataConnectorFieldMappingRequest
type DataConnectorFieldMappingRequest struct {
	Source string `json:"source"`
	Target string `json:"target"`
	Transform *string `json:"transform,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DataConnectorFieldMappingRequest DataConnectorFieldMappingRequest

// NewDataConnectorFieldMappingRequest instantiates a new DataConnectorFieldMappingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataConnectorFieldMappingRequest(source string, target string) *DataConnectorFieldMappingRequest {
	this := DataConnectorFieldMappingRequest{}
	this.Source = source
	this.Target = target
	var transform string = "none"
	this.Transform = &transform
	return &this
}

// NewDataConnectorFieldMappingRequestWithDefaults instantiates a new DataConnectorFieldMappingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataConnectorFieldMappingRequestWithDefaults() *DataConnectorFieldMappingRequest {
	this := DataConnectorFieldMappingRequest{}
	var transform string = "none"
	this.Transform = &transform
	return &this
}

// GetSource returns the Source field value
func (o *DataConnectorFieldMappingRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *DataConnectorFieldMappingRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *DataConnectorFieldMappingRequest) SetSource(v string) {
	o.Source = v
}

// GetTarget returns the Target field value
func (o *DataConnectorFieldMappingRequest) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *DataConnectorFieldMappingRequest) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *DataConnectorFieldMappingRequest) SetTarget(v string) {
	o.Target = v
}

// GetTransform returns the Transform field value if set, zero value otherwise.
func (o *DataConnectorFieldMappingRequest) GetTransform() string {
	if o == nil || IsNil(o.Transform) {
		var ret string
		return ret
	}
	return *o.Transform
}

// GetTransformOk returns a tuple with the Transform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataConnectorFieldMappingRequest) GetTransformOk() (*string, bool) {
	if o == nil || IsNil(o.Transform) {
		return nil, false
	}
	return o.Transform, true
}

// HasTransform returns a boolean if a field has been set.
func (o *DataConnectorFieldMappingRequest) HasTransform() bool {
	if o != nil && !IsNil(o.Transform) {
		return true
	}

	return false
}

// SetTransform gets a reference to the given string and assigns it to the Transform field.
func (o *DataConnectorFieldMappingRequest) SetTransform(v string) {
	o.Transform = &v
}

func (o DataConnectorFieldMappingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataConnectorFieldMappingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["target"] = o.Target
	if !IsNil(o.Transform) {
		toSerialize["transform"] = o.Transform
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DataConnectorFieldMappingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataConnectorFieldMappingRequest := _DataConnectorFieldMappingRequest{}

	err = json.Unmarshal(data, &varDataConnectorFieldMappingRequest)

	if err != nil {
		return err
	}

	*o = DataConnectorFieldMappingRequest(varDataConnectorFieldMappingRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source")
		delete(additionalProperties, "target")
		delete(additionalProperties, "transform")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDataConnectorFieldMappingRequest struct {
	value *DataConnectorFieldMappingRequest
	isSet bool
}

func (v NullableDataConnectorFieldMappingRequest) Get() *DataConnectorFieldMappingRequest {
	return v.value
}

func (v *NullableDataConnectorFieldMappingRequest) Set(val *DataConnectorFieldMappingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDataConnectorFieldMappingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDataConnectorFieldMappingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataConnectorFieldMappingRequest(val *DataConnectorFieldMappingRequest) *NullableDataConnectorFieldMappingRequest {
	return &NullableDataConnectorFieldMappingRequest{value: val, isSet: true}
}

func (v NullableDataConnectorFieldMappingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataConnectorFieldMappingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


