/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"fmt"
)

// checks if the CursorPageOfDataConnectorDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CursorPageOfDataConnectorDto{}

// CursorPageOfDataConnectorDto struct for CursorPageOfDataConnectorDto
type CursorPageOfDataConnectorDto struct {
	Items []DataConnectorDto `json:"items"`
	NextCursor NullableString `json:"nextCursor"`
	AdditionalProperties map[string]interface{}
}

type _CursorPageOfDataConnectorDto CursorPageOfDataConnectorDto

// NewCursorPageOfDataConnectorDto instantiates a new CursorPageOfDataConnectorDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPageOfDataConnectorDto(items []DataConnectorDto, nextCursor NullableString) *CursorPageOfDataConnectorDto {
	this := CursorPageOfDataConnectorDto{}
	this.Items = items
	this.NextCursor = nextCursor
	return &this
}

// NewCursorPageOfDataConnectorDtoWithDefaults instantiates a new CursorPageOfDataConnectorDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPageOfDataConnectorDtoWithDefaults() *CursorPageOfDataConnectorDto {
	this := CursorPageOfDataConnectorDto{}
	return &this
}

// GetItems returns the Items field value
func (o *CursorPageOfDataConnectorDto) GetItems() []DataConnectorDto {
	if o == nil {
		var ret []DataConnectorDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CursorPageOfDataConnectorDto) GetItemsOk() ([]DataConnectorDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CursorPageOfDataConnectorDto) SetItems(v []DataConnectorDto) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CursorPageOfDataConnectorDto) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CursorPageOfDataConnectorDto) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *CursorPageOfDataConnectorDto) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

func (o CursorPageOfDataConnectorDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CursorPageOfDataConnectorDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["nextCursor"] = o.NextCursor.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CursorPageOfDataConnectorDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"nextCursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCursorPageOfDataConnectorDto := _CursorPageOfDataConnectorDto{}

	err = json.Unmarshal(data, &varCursorPageOfDataConnectorDto)

	if err != nil {
		return err
	}

	*o = CursorPageOfDataConnectorDto(varCursorPageOfDataConnectorDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "nextCursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCursorPageOfDataConnectorDto struct {
	value *CursorPageOfDataConnectorDto
	isSet bool
}

func (v NullableCursorPageOfDataConnectorDto) Get() *CursorPageOfDataConnectorDto {
	return v.value
}

func (v *NullableCursorPageOfDataConnectorDto) Set(val *CursorPageOfDataConnectorDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPageOfDataConnectorDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPageOfDataConnectorDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPageOfDataConnectorDto(val *CursorPageOfDataConnectorDto) *NullableCursorPageOfDataConnectorDto {
	return &NullableCursorPageOfDataConnectorDto{value: val, isSet: true}
}

func (v NullableCursorPageOfDataConnectorDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPageOfDataConnectorDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


