/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"fmt"
)

// checks if the SchemaTableDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaTableDto{}

// SchemaTableDto struct for SchemaTableDto
type SchemaTableDto struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
	Columns []SchemaColumnDto `json:"columns"`
	AdditionalProperties map[string]interface{}
}

type _SchemaTableDto SchemaTableDto

// NewSchemaTableDto instantiates a new SchemaTableDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaTableDto(name string, kind string, columns []SchemaColumnDto) *SchemaTableDto {
	this := SchemaTableDto{}
	this.Name = name
	this.Kind = kind
	this.Columns = columns
	return &this
}

// NewSchemaTableDtoWithDefaults instantiates a new SchemaTableDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaTableDtoWithDefaults() *SchemaTableDto {
	this := SchemaTableDto{}
	return &this
}

// GetName returns the Name field value
func (o *SchemaTableDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SchemaTableDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SchemaTableDto) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *SchemaTableDto) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *SchemaTableDto) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *SchemaTableDto) SetKind(v string) {
	o.Kind = v
}

// GetColumns returns the Columns field value
func (o *SchemaTableDto) GetColumns() []SchemaColumnDto {
	if o == nil {
		var ret []SchemaColumnDto
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *SchemaTableDto) GetColumnsOk() ([]SchemaColumnDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Columns, true
}

// SetColumns sets field value
func (o *SchemaTableDto) SetColumns(v []SchemaColumnDto) {
	o.Columns = v
}

func (o SchemaTableDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaTableDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["kind"] = o.Kind
	toSerialize["columns"] = o.Columns

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SchemaTableDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"kind",
		"columns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchemaTableDto := _SchemaTableDto{}

	err = json.Unmarshal(data, &varSchemaTableDto)

	if err != nil {
		return err
	}

	*o = SchemaTableDto(varSchemaTableDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "columns")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSchemaTableDto struct {
	value *SchemaTableDto
	isSet bool
}

func (v NullableSchemaTableDto) Get() *SchemaTableDto {
	return v.value
}

func (v *NullableSchemaTableDto) Set(val *SchemaTableDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaTableDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaTableDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaTableDto(val *SchemaTableDto) *NullableSchemaTableDto {
	return &NullableSchemaTableDto{value: val, isSet: true}
}

func (v NullableSchemaTableDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaTableDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


