/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"fmt"
)

// checks if the TableDetailColumnDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableDetailColumnDto{}

// TableDetailColumnDto struct for TableDetailColumnDto
type TableDetailColumnDto struct {
	Name string `json:"name"`
	DataType string `json:"dataType"`
	IsNullable bool `json:"isNullable"`
	AdditionalProperties map[string]interface{}
}

type _TableDetailColumnDto TableDetailColumnDto

// NewTableDetailColumnDto instantiates a new TableDetailColumnDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableDetailColumnDto(name string, dataType string, isNullable bool) *TableDetailColumnDto {
	this := TableDetailColumnDto{}
	this.Name = name
	this.DataType = dataType
	this.IsNullable = isNullable
	return &this
}

// NewTableDetailColumnDtoWithDefaults instantiates a new TableDetailColumnDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableDetailColumnDtoWithDefaults() *TableDetailColumnDto {
	this := TableDetailColumnDto{}
	return &this
}

// GetName returns the Name field value
func (o *TableDetailColumnDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TableDetailColumnDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TableDetailColumnDto) SetName(v string) {
	o.Name = v
}

// GetDataType returns the DataType field value
func (o *TableDetailColumnDto) GetDataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value
// and a boolean to check if the value has been set.
func (o *TableDetailColumnDto) GetDataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataType, true
}

// SetDataType sets field value
func (o *TableDetailColumnDto) SetDataType(v string) {
	o.DataType = v
}

// GetIsNullable returns the IsNullable field value
func (o *TableDetailColumnDto) GetIsNullable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsNullable
}

// GetIsNullableOk returns a tuple with the IsNullable field value
// and a boolean to check if the value has been set.
func (o *TableDetailColumnDto) GetIsNullableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsNullable, true
}

// SetIsNullable sets field value
func (o *TableDetailColumnDto) SetIsNullable(v bool) {
	o.IsNullable = v
}

func (o TableDetailColumnDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableDetailColumnDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["dataType"] = o.DataType
	toSerialize["isNullable"] = o.IsNullable

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TableDetailColumnDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"dataType",
		"isNullable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableDetailColumnDto := _TableDetailColumnDto{}

	err = json.Unmarshal(data, &varTableDetailColumnDto)

	if err != nil {
		return err
	}

	*o = TableDetailColumnDto(varTableDetailColumnDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "dataType")
		delete(additionalProperties, "isNullable")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTableDetailColumnDto struct {
	value *TableDetailColumnDto
	isSet bool
}

func (v NullableTableDetailColumnDto) Get() *TableDetailColumnDto {
	return v.value
}

func (v *NullableTableDetailColumnDto) Set(val *TableDetailColumnDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTableDetailColumnDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTableDetailColumnDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableDetailColumnDto(val *TableDetailColumnDto) *NullableTableDetailColumnDto {
	return &NullableTableDetailColumnDto{value: val, isSet: true}
}

func (v NullableTableDetailColumnDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableDetailColumnDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


