/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"fmt"
)

// checks if the CursorPageOfTenantDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CursorPageOfTenantDto{}

// CursorPageOfTenantDto struct for CursorPageOfTenantDto
type CursorPageOfTenantDto struct {
	Items []TenantDto `json:"items"`
	NextCursor NullableString `json:"nextCursor"`
	AdditionalProperties map[string]interface{}
}

type _CursorPageOfTenantDto CursorPageOfTenantDto

// NewCursorPageOfTenantDto instantiates a new CursorPageOfTenantDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPageOfTenantDto(items []TenantDto, nextCursor NullableString) *CursorPageOfTenantDto {
	this := CursorPageOfTenantDto{}
	this.Items = items
	this.NextCursor = nextCursor
	return &this
}

// NewCursorPageOfTenantDtoWithDefaults instantiates a new CursorPageOfTenantDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPageOfTenantDtoWithDefaults() *CursorPageOfTenantDto {
	this := CursorPageOfTenantDto{}
	return &this
}

// GetItems returns the Items field value
func (o *CursorPageOfTenantDto) GetItems() []TenantDto {
	if o == nil {
		var ret []TenantDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CursorPageOfTenantDto) GetItemsOk() ([]TenantDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CursorPageOfTenantDto) SetItems(v []TenantDto) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CursorPageOfTenantDto) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CursorPageOfTenantDto) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *CursorPageOfTenantDto) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

func (o CursorPageOfTenantDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CursorPageOfTenantDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["nextCursor"] = o.NextCursor.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CursorPageOfTenantDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"nextCursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCursorPageOfTenantDto := _CursorPageOfTenantDto{}

	err = json.Unmarshal(data, &varCursorPageOfTenantDto)

	if err != nil {
		return err
	}

	*o = CursorPageOfTenantDto(varCursorPageOfTenantDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "nextCursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCursorPageOfTenantDto struct {
	value *CursorPageOfTenantDto
	isSet bool
}

func (v NullableCursorPageOfTenantDto) Get() *CursorPageOfTenantDto {
	return v.value
}

func (v *NullableCursorPageOfTenantDto) Set(val *CursorPageOfTenantDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPageOfTenantDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPageOfTenantDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPageOfTenantDto(val *CursorPageOfTenantDto) *NullableCursorPageOfTenantDto {
	return &NullableCursorPageOfTenantDto{value: val, isSet: true}
}

func (v NullableCursorPageOfTenantDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPageOfTenantDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


