/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"fmt"
)

// checks if the EjectedTableDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EjectedTableDto{}

// EjectedTableDto struct for EjectedTableDto
type EjectedTableDto struct {
	Schema string `json:"schema"`
	Table string `json:"table"`
	RowCount int64 `json:"rowCount"`
	Sha256 NullableString `json:"sha256"`
	Bytes NullableInt64 `json:"bytes"`
	AdditionalProperties map[string]interface{}
}

type _EjectedTableDto EjectedTableDto

// NewEjectedTableDto instantiates a new EjectedTableDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEjectedTableDto(schema string, table string, rowCount int64, sha256 NullableString, bytes NullableInt64) *EjectedTableDto {
	this := EjectedTableDto{}
	this.Schema = schema
	this.Table = table
	this.RowCount = rowCount
	this.Sha256 = sha256
	this.Bytes = bytes
	return &this
}

// NewEjectedTableDtoWithDefaults instantiates a new EjectedTableDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEjectedTableDtoWithDefaults() *EjectedTableDto {
	this := EjectedTableDto{}
	return &this
}

// GetSchema returns the Schema field value
func (o *EjectedTableDto) GetSchema() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *EjectedTableDto) GetSchemaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *EjectedTableDto) SetSchema(v string) {
	o.Schema = v
}

// GetTable returns the Table field value
func (o *EjectedTableDto) GetTable() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Table
}

// GetTableOk returns a tuple with the Table field value
// and a boolean to check if the value has been set.
func (o *EjectedTableDto) GetTableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Table, true
}

// SetTable sets field value
func (o *EjectedTableDto) SetTable(v string) {
	o.Table = v
}

// GetRowCount returns the RowCount field value
func (o *EjectedTableDto) GetRowCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value
// and a boolean to check if the value has been set.
func (o *EjectedTableDto) GetRowCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowCount, true
}

// SetRowCount sets field value
func (o *EjectedTableDto) SetRowCount(v int64) {
	o.RowCount = v
}

// GetSha256 returns the Sha256 field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EjectedTableDto) GetSha256() string {
	if o == nil || o.Sha256.Get() == nil {
		var ret string
		return ret
	}

	return *o.Sha256.Get()
}

// GetSha256Ok returns a tuple with the Sha256 field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EjectedTableDto) GetSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sha256.Get(), o.Sha256.IsSet()
}

// SetSha256 sets field value
func (o *EjectedTableDto) SetSha256(v string) {
	o.Sha256.Set(&v)
}

// GetBytes returns the Bytes field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *EjectedTableDto) GetBytes() int64 {
	if o == nil || o.Bytes.Get() == nil {
		var ret int64
		return ret
	}

	return *o.Bytes.Get()
}

// GetBytesOk returns a tuple with the Bytes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EjectedTableDto) GetBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bytes.Get(), o.Bytes.IsSet()
}

// SetBytes sets field value
func (o *EjectedTableDto) SetBytes(v int64) {
	o.Bytes.Set(&v)
}

func (o EjectedTableDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EjectedTableDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schema"] = o.Schema
	toSerialize["table"] = o.Table
	toSerialize["rowCount"] = o.RowCount
	toSerialize["sha256"] = o.Sha256.Get()
	toSerialize["bytes"] = o.Bytes.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EjectedTableDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schema",
		"table",
		"rowCount",
		"sha256",
		"bytes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEjectedTableDto := _EjectedTableDto{}

	err = json.Unmarshal(data, &varEjectedTableDto)

	if err != nil {
		return err
	}

	*o = EjectedTableDto(varEjectedTableDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "schema")
		delete(additionalProperties, "table")
		delete(additionalProperties, "rowCount")
		delete(additionalProperties, "sha256")
		delete(additionalProperties, "bytes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEjectedTableDto struct {
	value *EjectedTableDto
	isSet bool
}

func (v NullableEjectedTableDto) Get() *EjectedTableDto {
	return v.value
}

func (v *NullableEjectedTableDto) Set(val *EjectedTableDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEjectedTableDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEjectedTableDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEjectedTableDto(val *EjectedTableDto) *NullableEjectedTableDto {
	return &NullableEjectedTableDto{value: val, isSet: true}
}

func (v NullableEjectedTableDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEjectedTableDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


