/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
)

// checks if the UpdateTenantMemberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTenantMemberRequest{}

// UpdateTenantMemberRequest struct for UpdateTenantMemberRequest
type UpdateTenantMemberRequest struct {
	Role NullableString `json:"role,omitempty"`
	Status NullableString `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateTenantMemberRequest UpdateTenantMemberRequest

// NewUpdateTenantMemberRequest instantiates a new UpdateTenantMemberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTenantMemberRequest() *UpdateTenantMemberRequest {
	this := UpdateTenantMemberRequest{}
	return &this
}

// NewUpdateTenantMemberRequestWithDefaults instantiates a new UpdateTenantMemberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTenantMemberRequestWithDefaults() *UpdateTenantMemberRequest {
	this := UpdateTenantMemberRequest{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateTenantMemberRequest) GetRole() string {
	if o == nil || IsNil(o.Role.Get()) {
		var ret string
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTenantMemberRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *UpdateTenantMemberRequest) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableString and assigns it to the Role field.
func (o *UpdateTenantMemberRequest) SetRole(v string) {
	o.Role.Set(&v)
}
// SetRoleNil sets the value for Role to be an explicit nil
func (o *UpdateTenantMemberRequest) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *UpdateTenantMemberRequest) UnsetRole() {
	o.Role.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateTenantMemberRequest) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateTenantMemberRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateTenantMemberRequest) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *UpdateTenantMemberRequest) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *UpdateTenantMemberRequest) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *UpdateTenantMemberRequest) UnsetStatus() {
	o.Status.Unset()
}

func (o UpdateTenantMemberRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTenantMemberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateTenantMemberRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateTenantMemberRequest := _UpdateTenantMemberRequest{}

	err = json.Unmarshal(data, &varUpdateTenantMemberRequest)

	if err != nil {
		return err
	}

	*o = UpdateTenantMemberRequest(varUpdateTenantMemberRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "role")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateTenantMemberRequest struct {
	value *UpdateTenantMemberRequest
	isSet bool
}

func (v NullableUpdateTenantMemberRequest) Get() *UpdateTenantMemberRequest {
	return v.value
}

func (v *NullableUpdateTenantMemberRequest) Set(val *UpdateTenantMemberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTenantMemberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTenantMemberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTenantMemberRequest(val *UpdateTenantMemberRequest) *NullableUpdateTenantMemberRequest {
	return &NullableUpdateTenantMemberRequest{value: val, isSet: true}
}

func (v NullableUpdateTenantMemberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTenantMemberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


