/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the SystemSettingsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemSettingsDto{}

// SystemSettingsDto struct for SystemSettingsDto
type SystemSettingsDto struct {
	McpEnabled bool `json:"mcpEnabled"`
	McpAllowWrites bool `json:"mcpAllowWrites"`
	McpAllowOperatorCommands *bool `json:"mcpAllowOperatorCommands,omitempty"`
	McpMaxRowsPerResult int32 `json:"mcpMaxRowsPerResult"`
	McpPublicBaseUrl string `json:"mcpPublicBaseUrl"`
	McpRoute string `json:"mcpRoute"`
	Version int32 `json:"version"`
	UpdatedUtc NullableTime `json:"updatedUtc"`
	AdditionalProperties map[string]interface{}
}

type _SystemSettingsDto SystemSettingsDto

// NewSystemSettingsDto instantiates a new SystemSettingsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemSettingsDto(mcpEnabled bool, mcpAllowWrites bool, mcpMaxRowsPerResult int32, mcpPublicBaseUrl string, mcpRoute string, version int32, updatedUtc NullableTime) *SystemSettingsDto {
	this := SystemSettingsDto{}
	this.McpEnabled = mcpEnabled
	this.McpAllowWrites = mcpAllowWrites
	this.McpMaxRowsPerResult = mcpMaxRowsPerResult
	this.McpPublicBaseUrl = mcpPublicBaseUrl
	this.McpRoute = mcpRoute
	this.Version = version
	this.UpdatedUtc = updatedUtc
	return &this
}

// NewSystemSettingsDtoWithDefaults instantiates a new SystemSettingsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemSettingsDtoWithDefaults() *SystemSettingsDto {
	this := SystemSettingsDto{}
	return &this
}

// GetMcpEnabled returns the McpEnabled field value
func (o *SystemSettingsDto) GetMcpEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.McpEnabled
}

// GetMcpEnabledOk returns a tuple with the McpEnabled field value
// and a boolean to check if the value has been set.
func (o *SystemSettingsDto) GetMcpEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpEnabled, true
}

// SetMcpEnabled sets field value
func (o *SystemSettingsDto) SetMcpEnabled(v bool) {
	o.McpEnabled = v
}

// GetMcpAllowWrites returns the McpAllowWrites field value
func (o *SystemSettingsDto) GetMcpAllowWrites() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.McpAllowWrites
}

// GetMcpAllowWritesOk returns a tuple with the McpAllowWrites field value
// and a boolean to check if the value has been set.
func (o *SystemSettingsDto) GetMcpAllowWritesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpAllowWrites, true
}

// SetMcpAllowWrites sets field value
func (o *SystemSettingsDto) SetMcpAllowWrites(v bool) {
	o.McpAllowWrites = v
}

// GetMcpAllowOperatorCommands returns the McpAllowOperatorCommands field value if set, zero value otherwise.
func (o *SystemSettingsDto) GetMcpAllowOperatorCommands() bool {
	if o == nil || IsNil(o.McpAllowOperatorCommands) {
		var ret bool
		return ret
	}
	return *o.McpAllowOperatorCommands
}

// GetMcpAllowOperatorCommandsOk returns a tuple with the McpAllowOperatorCommands field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSettingsDto) GetMcpAllowOperatorCommandsOk() (*bool, bool) {
	if o == nil || IsNil(o.McpAllowOperatorCommands) {
		return nil, false
	}
	return o.McpAllowOperatorCommands, true
}

// HasMcpAllowOperatorCommands returns a boolean if a field has been set.
func (o *SystemSettingsDto) HasMcpAllowOperatorCommands() bool {
	if o != nil && !IsNil(o.McpAllowOperatorCommands) {
		return true
	}

	return false
}

// SetMcpAllowOperatorCommands gets a reference to the given bool and assigns it to the McpAllowOperatorCommands field.
func (o *SystemSettingsDto) SetMcpAllowOperatorCommands(v bool) {
	o.McpAllowOperatorCommands = &v
}

// GetMcpMaxRowsPerResult returns the McpMaxRowsPerResult field value
func (o *SystemSettingsDto) GetMcpMaxRowsPerResult() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.McpMaxRowsPerResult
}

// GetMcpMaxRowsPerResultOk returns a tuple with the McpMaxRowsPerResult field value
// and a boolean to check if the value has been set.
func (o *SystemSettingsDto) GetMcpMaxRowsPerResultOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpMaxRowsPerResult, true
}

// SetMcpMaxRowsPerResult sets field value
func (o *SystemSettingsDto) SetMcpMaxRowsPerResult(v int32) {
	o.McpMaxRowsPerResult = v
}

// GetMcpPublicBaseUrl returns the McpPublicBaseUrl field value
func (o *SystemSettingsDto) GetMcpPublicBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.McpPublicBaseUrl
}

// GetMcpPublicBaseUrlOk returns a tuple with the McpPublicBaseUrl field value
// and a boolean to check if the value has been set.
func (o *SystemSettingsDto) GetMcpPublicBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpPublicBaseUrl, true
}

// SetMcpPublicBaseUrl sets field value
func (o *SystemSettingsDto) SetMcpPublicBaseUrl(v string) {
	o.McpPublicBaseUrl = v
}

// GetMcpRoute returns the McpRoute field value
func (o *SystemSettingsDto) GetMcpRoute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.McpRoute
}

// GetMcpRouteOk returns a tuple with the McpRoute field value
// and a boolean to check if the value has been set.
func (o *SystemSettingsDto) GetMcpRouteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.McpRoute, true
}

// SetMcpRoute sets field value
func (o *SystemSettingsDto) SetMcpRoute(v string) {
	o.McpRoute = v
}

// GetVersion returns the Version field value
func (o *SystemSettingsDto) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *SystemSettingsDto) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *SystemSettingsDto) SetVersion(v int32) {
	o.Version = v
}

// GetUpdatedUtc returns the UpdatedUtc field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *SystemSettingsDto) GetUpdatedUtc() time.Time {
	if o == nil || o.UpdatedUtc.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.UpdatedUtc.Get()
}

// GetUpdatedUtcOk returns a tuple with the UpdatedUtc field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemSettingsDto) GetUpdatedUtcOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedUtc.Get(), o.UpdatedUtc.IsSet()
}

// SetUpdatedUtc sets field value
func (o *SystemSettingsDto) SetUpdatedUtc(v time.Time) {
	o.UpdatedUtc.Set(&v)
}

func (o SystemSettingsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemSettingsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mcpEnabled"] = o.McpEnabled
	toSerialize["mcpAllowWrites"] = o.McpAllowWrites
	if !IsNil(o.McpAllowOperatorCommands) {
		toSerialize["mcpAllowOperatorCommands"] = o.McpAllowOperatorCommands
	}
	toSerialize["mcpMaxRowsPerResult"] = o.McpMaxRowsPerResult
	toSerialize["mcpPublicBaseUrl"] = o.McpPublicBaseUrl
	toSerialize["mcpRoute"] = o.McpRoute
	toSerialize["version"] = o.Version
	toSerialize["updatedUtc"] = o.UpdatedUtc.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SystemSettingsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mcpEnabled",
		"mcpAllowWrites",
		"mcpMaxRowsPerResult",
		"mcpPublicBaseUrl",
		"mcpRoute",
		"version",
		"updatedUtc",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemSettingsDto := _SystemSettingsDto{}

	err = json.Unmarshal(data, &varSystemSettingsDto)

	if err != nil {
		return err
	}

	*o = SystemSettingsDto(varSystemSettingsDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mcpEnabled")
		delete(additionalProperties, "mcpAllowWrites")
		delete(additionalProperties, "mcpAllowOperatorCommands")
		delete(additionalProperties, "mcpMaxRowsPerResult")
		delete(additionalProperties, "mcpPublicBaseUrl")
		delete(additionalProperties, "mcpRoute")
		delete(additionalProperties, "version")
		delete(additionalProperties, "updatedUtc")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemSettingsDto struct {
	value *SystemSettingsDto
	isSet bool
}

func (v NullableSystemSettingsDto) Get() *SystemSettingsDto {
	return v.value
}

func (v *NullableSystemSettingsDto) Set(val *SystemSettingsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemSettingsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemSettingsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemSettingsDto(val *SystemSettingsDto) *NullableSystemSettingsDto {
	return &NullableSystemSettingsDto{value: val, isSet: true}
}

func (v NullableSystemSettingsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemSettingsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


