/*
LakeHold Public API

Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lakehold

import (
	"encoding/json"
	"fmt"
)

// checks if the QueryDiagnostic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryDiagnostic{}

// QueryDiagnostic struct for QueryDiagnostic
type QueryDiagnostic struct {
	Severity string `json:"severity"`
	Code string `json:"code"`
	Message string `json:"message"`
	StartLine int32 `json:"startLine"`
	StartColumn int32 `json:"startColumn"`
	EndLine int32 `json:"endLine"`
	EndColumn int32 `json:"endColumn"`
	AdditionalProperties map[string]interface{}
}

type _QueryDiagnostic QueryDiagnostic

// NewQueryDiagnostic instantiates a new QueryDiagnostic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryDiagnostic(severity string, code string, message string, startLine int32, startColumn int32, endLine int32, endColumn int32) *QueryDiagnostic {
	this := QueryDiagnostic{}
	this.Severity = severity
	this.Code = code
	this.Message = message
	this.StartLine = startLine
	this.StartColumn = startColumn
	this.EndLine = endLine
	this.EndColumn = endColumn
	return &this
}

// NewQueryDiagnosticWithDefaults instantiates a new QueryDiagnostic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryDiagnosticWithDefaults() *QueryDiagnostic {
	this := QueryDiagnostic{}
	return &this
}

// GetSeverity returns the Severity field value
func (o *QueryDiagnostic) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *QueryDiagnostic) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *QueryDiagnostic) SetSeverity(v string) {
	o.Severity = v
}

// GetCode returns the Code field value
func (o *QueryDiagnostic) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *QueryDiagnostic) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *QueryDiagnostic) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *QueryDiagnostic) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *QueryDiagnostic) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *QueryDiagnostic) SetMessage(v string) {
	o.Message = v
}

// GetStartLine returns the StartLine field value
func (o *QueryDiagnostic) GetStartLine() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartLine
}

// GetStartLineOk returns a tuple with the StartLine field value
// and a boolean to check if the value has been set.
func (o *QueryDiagnostic) GetStartLineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartLine, true
}

// SetStartLine sets field value
func (o *QueryDiagnostic) SetStartLine(v int32) {
	o.StartLine = v
}

// GetStartColumn returns the StartColumn field value
func (o *QueryDiagnostic) GetStartColumn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartColumn
}

// GetStartColumnOk returns a tuple with the StartColumn field value
// and a boolean to check if the value has been set.
func (o *QueryDiagnostic) GetStartColumnOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartColumn, true
}

// SetStartColumn sets field value
func (o *QueryDiagnostic) SetStartColumn(v int32) {
	o.StartColumn = v
}

// GetEndLine returns the EndLine field value
func (o *QueryDiagnostic) GetEndLine() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndLine
}

// GetEndLineOk returns a tuple with the EndLine field value
// and a boolean to check if the value has been set.
func (o *QueryDiagnostic) GetEndLineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndLine, true
}

// SetEndLine sets field value
func (o *QueryDiagnostic) SetEndLine(v int32) {
	o.EndLine = v
}

// GetEndColumn returns the EndColumn field value
func (o *QueryDiagnostic) GetEndColumn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndColumn
}

// GetEndColumnOk returns a tuple with the EndColumn field value
// and a boolean to check if the value has been set.
func (o *QueryDiagnostic) GetEndColumnOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndColumn, true
}

// SetEndColumn sets field value
func (o *QueryDiagnostic) SetEndColumn(v int32) {
	o.EndColumn = v
}

func (o QueryDiagnostic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryDiagnostic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["severity"] = o.Severity
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	toSerialize["startLine"] = o.StartLine
	toSerialize["startColumn"] = o.StartColumn
	toSerialize["endLine"] = o.EndLine
	toSerialize["endColumn"] = o.EndColumn

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QueryDiagnostic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"severity",
		"code",
		"message",
		"startLine",
		"startColumn",
		"endLine",
		"endColumn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryDiagnostic := _QueryDiagnostic{}

	err = json.Unmarshal(data, &varQueryDiagnostic)

	if err != nil {
		return err
	}

	*o = QueryDiagnostic(varQueryDiagnostic)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "severity")
		delete(additionalProperties, "code")
		delete(additionalProperties, "message")
		delete(additionalProperties, "startLine")
		delete(additionalProperties, "startColumn")
		delete(additionalProperties, "endLine")
		delete(additionalProperties, "endColumn")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQueryDiagnostic struct {
	value *QueryDiagnostic
	isSet bool
}

func (v NullableQueryDiagnostic) Get() *QueryDiagnostic {
	return v.value
}

func (v *NullableQueryDiagnostic) Set(val *QueryDiagnostic) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryDiagnostic) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryDiagnostic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryDiagnostic(val *QueryDiagnostic) *NullableQueryDiagnostic {
	return &NullableQueryDiagnostic{value: val, isSet: true}
}

func (v NullableQueryDiagnostic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryDiagnostic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


