/*
 * LakeHold Public API
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakehold.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lakehold.sdk.JSON;

/**
 * DataConnectorSourceSettingsRequest
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class DataConnectorSourceSettingsRequest {
  public static final String SERIALIZED_NAME_SOURCE_TABLE = "sourceTable";
  @SerializedName(SERIALIZED_NAME_SOURCE_TABLE)
  @jakarta.annotation.Nullable
  private String sourceTable;

  public static final String SERIALIZED_NAME_CURSOR_COLUMN = "cursorColumn";
  @SerializedName(SERIALIZED_NAME_CURSOR_COLUMN)
  @jakarta.annotation.Nullable
  private String cursorColumn;

  public static final String SERIALIZED_NAME_CURSOR_TYPE = "cursorType";
  @SerializedName(SERIALIZED_NAME_CURSOR_TYPE)
  @jakarta.annotation.Nullable
  private String cursorType;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "pageSize";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  @jakarta.annotation.Nullable
  private Integer pageSize = 100;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  @jakarta.annotation.Nullable
  private List<String> properties;

  public static final String SERIALIZED_NAME_CURSOR_IS_COMMIT_MONOTONIC = "cursorIsCommitMonotonic";
  @SerializedName(SERIALIZED_NAME_CURSOR_IS_COMMIT_MONOTONIC)
  @jakarta.annotation.Nullable
  private Boolean cursorIsCommitMonotonic = false;

  public DataConnectorSourceSettingsRequest() {
  }

  public DataConnectorSourceSettingsRequest sourceTable(@jakarta.annotation.Nullable String sourceTable) {
    this.sourceTable = sourceTable;
    return this;
  }

  /**
   * Get sourceTable
   * @return sourceTable
   */
  @jakarta.annotation.Nullable
  public String getSourceTable() {
    return sourceTable;
  }

  public void setSourceTable(@jakarta.annotation.Nullable String sourceTable) {
    this.sourceTable = sourceTable;
  }


  public DataConnectorSourceSettingsRequest cursorColumn(@jakarta.annotation.Nullable String cursorColumn) {
    this.cursorColumn = cursorColumn;
    return this;
  }

  /**
   * Get cursorColumn
   * @return cursorColumn
   */
  @jakarta.annotation.Nullable
  public String getCursorColumn() {
    return cursorColumn;
  }

  public void setCursorColumn(@jakarta.annotation.Nullable String cursorColumn) {
    this.cursorColumn = cursorColumn;
  }


  public DataConnectorSourceSettingsRequest cursorType(@jakarta.annotation.Nullable String cursorType) {
    this.cursorType = cursorType;
    return this;
  }

  /**
   * Get cursorType
   * @return cursorType
   */
  @jakarta.annotation.Nullable
  public String getCursorType() {
    return cursorType;
  }

  public void setCursorType(@jakarta.annotation.Nullable String cursorType) {
    this.cursorType = cursorType;
  }


  public DataConnectorSourceSettingsRequest pageSize(@jakarta.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Get pageSize
   * @return pageSize
   */
  @jakarta.annotation.Nullable
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(@jakarta.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }


  public DataConnectorSourceSettingsRequest properties(@jakarta.annotation.Nullable List<String> properties) {
    this.properties = properties;
    return this;
  }

  public DataConnectorSourceSettingsRequest addPropertiesItem(String propertiesItem) {
    if (this.properties == null) {
      this.properties = new ArrayList<>();
    }
    this.properties.add(propertiesItem);
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @jakarta.annotation.Nullable
  public List<String> getProperties() {
    return properties;
  }

  public void setProperties(@jakarta.annotation.Nullable List<String> properties) {
    this.properties = properties;
  }


  public DataConnectorSourceSettingsRequest cursorIsCommitMonotonic(@jakarta.annotation.Nullable Boolean cursorIsCommitMonotonic) {
    this.cursorIsCommitMonotonic = cursorIsCommitMonotonic;
    return this;
  }

  /**
   * Get cursorIsCommitMonotonic
   * @return cursorIsCommitMonotonic
   */
  @jakarta.annotation.Nullable
  public Boolean getCursorIsCommitMonotonic() {
    return cursorIsCommitMonotonic;
  }

  public void setCursorIsCommitMonotonic(@jakarta.annotation.Nullable Boolean cursorIsCommitMonotonic) {
    this.cursorIsCommitMonotonic = cursorIsCommitMonotonic;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DataConnectorSourceSettingsRequest instance itself
   */
  public DataConnectorSourceSettingsRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataConnectorSourceSettingsRequest dataConnectorSourceSettingsRequest = (DataConnectorSourceSettingsRequest) o;
    return Objects.equals(this.sourceTable, dataConnectorSourceSettingsRequest.sourceTable) &&
        Objects.equals(this.cursorColumn, dataConnectorSourceSettingsRequest.cursorColumn) &&
        Objects.equals(this.cursorType, dataConnectorSourceSettingsRequest.cursorType) &&
        Objects.equals(this.pageSize, dataConnectorSourceSettingsRequest.pageSize) &&
        Objects.equals(this.properties, dataConnectorSourceSettingsRequest.properties) &&
        Objects.equals(this.cursorIsCommitMonotonic, dataConnectorSourceSettingsRequest.cursorIsCommitMonotonic)&&
        Objects.equals(this.additionalProperties, dataConnectorSourceSettingsRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceTable, cursorColumn, cursorType, pageSize, properties, cursorIsCommitMonotonic, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataConnectorSourceSettingsRequest {\n");
    sb.append("    sourceTable: ").append(toIndentedString(sourceTable)).append("\n");
    sb.append("    cursorColumn: ").append(toIndentedString(cursorColumn)).append("\n");
    sb.append("    cursorType: ").append(toIndentedString(cursorType)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    cursorIsCommitMonotonic: ").append(toIndentedString(cursorIsCommitMonotonic)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("sourceTable", "cursorColumn", "cursorType", "pageSize", "properties", "cursorIsCommitMonotonic"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DataConnectorSourceSettingsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DataConnectorSourceSettingsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DataConnectorSourceSettingsRequest is not found in the empty JSON string", DataConnectorSourceSettingsRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("sourceTable") != null && !jsonObj.get("sourceTable").isJsonNull()) && !jsonObj.get("sourceTable").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sourceTable` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sourceTable").toString()));
      }
      if ((jsonObj.get("cursorColumn") != null && !jsonObj.get("cursorColumn").isJsonNull()) && !jsonObj.get("cursorColumn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cursorColumn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cursorColumn").toString()));
      }
      if ((jsonObj.get("cursorType") != null && !jsonObj.get("cursorType").isJsonNull()) && !jsonObj.get("cursorType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cursorType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cursorType").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("properties") != null && !jsonObj.get("properties").isJsonNull() && !jsonObj.get("properties").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `properties` to be an array in the JSON string but got `%s`", jsonObj.get("properties").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DataConnectorSourceSettingsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DataConnectorSourceSettingsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DataConnectorSourceSettingsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DataConnectorSourceSettingsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DataConnectorSourceSettingsRequest>() {
           @Override
           public void write(JsonWriter out, DataConnectorSourceSettingsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DataConnectorSourceSettingsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             DataConnectorSourceSettingsRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DataConnectorSourceSettingsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DataConnectorSourceSettingsRequest
   * @throws IOException if the JSON string is invalid with respect to DataConnectorSourceSettingsRequest
   */
  public static DataConnectorSourceSettingsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DataConnectorSourceSettingsRequest.class);
  }

  /**
   * Convert an instance of DataConnectorSourceSettingsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

