/*
 * LakeHold Public API
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakehold.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lakehold.sdk.JSON;

/**
 * QueryRunDto
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class QueryRunDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @jakarta.annotation.Nonnull
  private Integer id;

  public static final String SERIALIZED_NAME_CATALOG_NAME = "catalogName";
  @SerializedName(SERIALIZED_NAME_CATALOG_NAME)
  @jakarta.annotation.Nonnull
  private String catalogName;

  public static final String SERIALIZED_NAME_SQL = "sql";
  @SerializedName(SERIALIZED_NAME_SQL)
  @jakarta.annotation.Nonnull
  private String sql;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  @jakarta.annotation.Nonnull
  private String language;

  public static final String SERIALIZED_NAME_STARTED_UTC = "startedUtc";
  @SerializedName(SERIALIZED_NAME_STARTED_UTC)
  @jakarta.annotation.Nonnull
  private OffsetDateTime startedUtc;

  public static final String SERIALIZED_NAME_ELAPSED_MILLISECONDS = "elapsedMilliseconds";
  @SerializedName(SERIALIZED_NAME_ELAPSED_MILLISECONDS)
  @jakarta.annotation.Nonnull
  private Double elapsedMilliseconds;

  public static final String SERIALIZED_NAME_ROW_COUNT = "rowCount";
  @SerializedName(SERIALIZED_NAME_ROW_COUNT)
  @jakarta.annotation.Nonnull
  private Integer rowCount;

  public static final String SERIALIZED_NAME_SUCCEEDED = "succeeded";
  @SerializedName(SERIALIZED_NAME_SUCCEEDED)
  @jakarta.annotation.Nonnull
  private Boolean succeeded;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @jakarta.annotation.Nullable
  private String error;

  public static final String SERIALIZED_NAME_TOKEN_ID = "tokenId";
  @SerializedName(SERIALIZED_NAME_TOKEN_ID)
  @jakarta.annotation.Nullable
  private Integer tokenId;

  public static final String SERIALIZED_NAME_TOKEN_NAME = "tokenName";
  @SerializedName(SERIALIZED_NAME_TOKEN_NAME)
  @jakarta.annotation.Nullable
  private String tokenName;

  public QueryRunDto() {
  }

  public QueryRunDto id(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  public Integer getId() {
    return id;
  }

  public void setId(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public QueryRunDto catalogName(@jakarta.annotation.Nonnull String catalogName) {
    this.catalogName = catalogName;
    return this;
  }

  /**
   * Get catalogName
   * @return catalogName
   */
  @jakarta.annotation.Nonnull
  public String getCatalogName() {
    return catalogName;
  }

  public void setCatalogName(@jakarta.annotation.Nonnull String catalogName) {
    this.catalogName = catalogName;
  }


  public QueryRunDto sql(@jakarta.annotation.Nonnull String sql) {
    this.sql = sql;
    return this;
  }

  /**
   * Get sql
   * @return sql
   */
  @jakarta.annotation.Nonnull
  public String getSql() {
    return sql;
  }

  public void setSql(@jakarta.annotation.Nonnull String sql) {
    this.sql = sql;
  }


  public QueryRunDto language(@jakarta.annotation.Nonnull String language) {
    this.language = language;
    return this;
  }

  /**
   * Get language
   * @return language
   */
  @jakarta.annotation.Nonnull
  public String getLanguage() {
    return language;
  }

  public void setLanguage(@jakarta.annotation.Nonnull String language) {
    this.language = language;
  }


  public QueryRunDto startedUtc(@jakarta.annotation.Nonnull OffsetDateTime startedUtc) {
    this.startedUtc = startedUtc;
    return this;
  }

  /**
   * Get startedUtc
   * @return startedUtc
   */
  @jakarta.annotation.Nonnull
  public OffsetDateTime getStartedUtc() {
    return startedUtc;
  }

  public void setStartedUtc(@jakarta.annotation.Nonnull OffsetDateTime startedUtc) {
    this.startedUtc = startedUtc;
  }


  public QueryRunDto elapsedMilliseconds(@jakarta.annotation.Nonnull Double elapsedMilliseconds) {
    this.elapsedMilliseconds = elapsedMilliseconds;
    return this;
  }

  /**
   * Get elapsedMilliseconds
   * @return elapsedMilliseconds
   */
  @jakarta.annotation.Nonnull
  public Double getElapsedMilliseconds() {
    return elapsedMilliseconds;
  }

  public void setElapsedMilliseconds(@jakarta.annotation.Nonnull Double elapsedMilliseconds) {
    this.elapsedMilliseconds = elapsedMilliseconds;
  }


  public QueryRunDto rowCount(@jakarta.annotation.Nonnull Integer rowCount) {
    this.rowCount = rowCount;
    return this;
  }

  /**
   * Get rowCount
   * @return rowCount
   */
  @jakarta.annotation.Nonnull
  public Integer getRowCount() {
    return rowCount;
  }

  public void setRowCount(@jakarta.annotation.Nonnull Integer rowCount) {
    this.rowCount = rowCount;
  }


  public QueryRunDto succeeded(@jakarta.annotation.Nonnull Boolean succeeded) {
    this.succeeded = succeeded;
    return this;
  }

  /**
   * Get succeeded
   * @return succeeded
   */
  @jakarta.annotation.Nonnull
  public Boolean getSucceeded() {
    return succeeded;
  }

  public void setSucceeded(@jakarta.annotation.Nonnull Boolean succeeded) {
    this.succeeded = succeeded;
  }


  public QueryRunDto error(@jakarta.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @jakarta.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(@jakarta.annotation.Nullable String error) {
    this.error = error;
  }


  public QueryRunDto tokenId(@jakarta.annotation.Nullable Integer tokenId) {
    this.tokenId = tokenId;
    return this;
  }

  /**
   * Get tokenId
   * @return tokenId
   */
  @jakarta.annotation.Nullable
  public Integer getTokenId() {
    return tokenId;
  }

  public void setTokenId(@jakarta.annotation.Nullable Integer tokenId) {
    this.tokenId = tokenId;
  }


  public QueryRunDto tokenName(@jakarta.annotation.Nullable String tokenName) {
    this.tokenName = tokenName;
    return this;
  }

  /**
   * Get tokenName
   * @return tokenName
   */
  @jakarta.annotation.Nullable
  public String getTokenName() {
    return tokenName;
  }

  public void setTokenName(@jakarta.annotation.Nullable String tokenName) {
    this.tokenName = tokenName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the QueryRunDto instance itself
   */
  public QueryRunDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryRunDto queryRunDto = (QueryRunDto) o;
    return Objects.equals(this.id, queryRunDto.id) &&
        Objects.equals(this.catalogName, queryRunDto.catalogName) &&
        Objects.equals(this.sql, queryRunDto.sql) &&
        Objects.equals(this.language, queryRunDto.language) &&
        Objects.equals(this.startedUtc, queryRunDto.startedUtc) &&
        Objects.equals(this.elapsedMilliseconds, queryRunDto.elapsedMilliseconds) &&
        Objects.equals(this.rowCount, queryRunDto.rowCount) &&
        Objects.equals(this.succeeded, queryRunDto.succeeded) &&
        Objects.equals(this.error, queryRunDto.error) &&
        Objects.equals(this.tokenId, queryRunDto.tokenId) &&
        Objects.equals(this.tokenName, queryRunDto.tokenName)&&
        Objects.equals(this.additionalProperties, queryRunDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, catalogName, sql, language, startedUtc, elapsedMilliseconds, rowCount, succeeded, error, tokenId, tokenName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryRunDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    catalogName: ").append(toIndentedString(catalogName)).append("\n");
    sb.append("    sql: ").append(toIndentedString(sql)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    startedUtc: ").append(toIndentedString(startedUtc)).append("\n");
    sb.append("    elapsedMilliseconds: ").append(toIndentedString(elapsedMilliseconds)).append("\n");
    sb.append("    rowCount: ").append(toIndentedString(rowCount)).append("\n");
    sb.append("    succeeded: ").append(toIndentedString(succeeded)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    tokenName: ").append(toIndentedString(tokenName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "catalogName", "sql", "language", "startedUtc", "elapsedMilliseconds", "rowCount", "succeeded", "error", "tokenId", "tokenName"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "catalogName", "sql", "language", "startedUtc", "elapsedMilliseconds", "rowCount", "succeeded", "error", "tokenId", "tokenName"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QueryRunDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QueryRunDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QueryRunDto is not found in the empty JSON string", QueryRunDto.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : QueryRunDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("catalogName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `catalogName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("catalogName").toString()));
      }
      if (!jsonObj.get("sql").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sql` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sql").toString()));
      }
      if (!jsonObj.get("language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("language").toString()));
      }
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
      if ((jsonObj.get("tokenName") != null && !jsonObj.get("tokenName").isJsonNull()) && !jsonObj.get("tokenName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tokenName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tokenName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QueryRunDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QueryRunDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QueryRunDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QueryRunDto.class));

       return (TypeAdapter<T>) new TypeAdapter<QueryRunDto>() {
           @Override
           public void write(JsonWriter out, QueryRunDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public QueryRunDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             QueryRunDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QueryRunDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QueryRunDto
   * @throws IOException if the JSON string is invalid with respect to QueryRunDto
   */
  public static QueryRunDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QueryRunDto.class);
  }

  /**
   * Convert an instance of QueryRunDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

