/*
 * LakeHold Public API
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakehold.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.lakehold.sdk.model.ColumnDto;
import io.lakehold.sdk.model.QueryDiagnostic;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lakehold.sdk.JSON;

/**
 * QueryResponse
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class QueryResponse {
  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  @jakarta.annotation.Nonnull
  private List<ColumnDto> columns = new ArrayList<>();

  public static final String SERIALIZED_NAME_ROWS = "rows";
  @SerializedName(SERIALIZED_NAME_ROWS)
  @jakarta.annotation.Nonnull
  private List<List<Object>> rows = new ArrayList<>();

  public static final String SERIALIZED_NAME_TRUNCATED = "truncated";
  @SerializedName(SERIALIZED_NAME_TRUNCATED)
  @jakarta.annotation.Nonnull
  private Boolean truncated;

  public static final String SERIALIZED_NAME_ELAPSED_MILLISECONDS = "elapsedMilliseconds";
  @SerializedName(SERIALIZED_NAME_ELAPSED_MILLISECONDS)
  @jakarta.annotation.Nonnull
  private Double elapsedMilliseconds;

  public static final String SERIALIZED_NAME_ROWS_AFFECTED = "rowsAffected";
  @SerializedName(SERIALIZED_NAME_ROWS_AFFECTED)
  @jakarta.annotation.Nullable
  private Long rowsAffected;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  @jakarta.annotation.Nonnull
  private String language;

  public static final String SERIALIZED_NAME_GENERATED_SQL = "generatedSql";
  @SerializedName(SERIALIZED_NAME_GENERATED_SQL)
  @jakarta.annotation.Nullable
  private String generatedSql;

  public static final String SERIALIZED_NAME_DIAGNOSTICS = "diagnostics";
  @SerializedName(SERIALIZED_NAME_DIAGNOSTICS)
  @jakarta.annotation.Nonnull
  private List<QueryDiagnostic> diagnostics = new ArrayList<>();

  public QueryResponse() {
  }

  public QueryResponse columns(@jakarta.annotation.Nonnull List<ColumnDto> columns) {
    this.columns = columns;
    return this;
  }

  public QueryResponse addColumnsItem(ColumnDto columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * Get columns
   * @return columns
   */
  @jakarta.annotation.Nonnull
  public List<ColumnDto> getColumns() {
    return columns;
  }

  public void setColumns(@jakarta.annotation.Nonnull List<ColumnDto> columns) {
    this.columns = columns;
  }


  public QueryResponse rows(@jakarta.annotation.Nonnull List<List<Object>> rows) {
    this.rows = rows;
    return this;
  }

  public QueryResponse addRowsItem(List<Object> rowsItem) {
    if (this.rows == null) {
      this.rows = new ArrayList<>();
    }
    this.rows.add(rowsItem);
    return this;
  }

  /**
   * Get rows
   * @return rows
   */
  @jakarta.annotation.Nonnull
  public List<List<Object>> getRows() {
    return rows;
  }

  public void setRows(@jakarta.annotation.Nonnull List<List<Object>> rows) {
    this.rows = rows;
  }


  public QueryResponse truncated(@jakarta.annotation.Nonnull Boolean truncated) {
    this.truncated = truncated;
    return this;
  }

  /**
   * Get truncated
   * @return truncated
   */
  @jakarta.annotation.Nonnull
  public Boolean getTruncated() {
    return truncated;
  }

  public void setTruncated(@jakarta.annotation.Nonnull Boolean truncated) {
    this.truncated = truncated;
  }


  public QueryResponse elapsedMilliseconds(@jakarta.annotation.Nonnull Double elapsedMilliseconds) {
    this.elapsedMilliseconds = elapsedMilliseconds;
    return this;
  }

  /**
   * Get elapsedMilliseconds
   * @return elapsedMilliseconds
   */
  @jakarta.annotation.Nonnull
  public Double getElapsedMilliseconds() {
    return elapsedMilliseconds;
  }

  public void setElapsedMilliseconds(@jakarta.annotation.Nonnull Double elapsedMilliseconds) {
    this.elapsedMilliseconds = elapsedMilliseconds;
  }


  public QueryResponse rowsAffected(@jakarta.annotation.Nullable Long rowsAffected) {
    this.rowsAffected = rowsAffected;
    return this;
  }

  /**
   * Get rowsAffected
   * @return rowsAffected
   */
  @jakarta.annotation.Nullable
  public Long getRowsAffected() {
    return rowsAffected;
  }

  public void setRowsAffected(@jakarta.annotation.Nullable Long rowsAffected) {
    this.rowsAffected = rowsAffected;
  }


  public QueryResponse language(@jakarta.annotation.Nonnull String language) {
    this.language = language;
    return this;
  }

  /**
   * Get language
   * @return language
   */
  @jakarta.annotation.Nonnull
  public String getLanguage() {
    return language;
  }

  public void setLanguage(@jakarta.annotation.Nonnull String language) {
    this.language = language;
  }


  public QueryResponse generatedSql(@jakarta.annotation.Nullable String generatedSql) {
    this.generatedSql = generatedSql;
    return this;
  }

  /**
   * Get generatedSql
   * @return generatedSql
   */
  @jakarta.annotation.Nullable
  public String getGeneratedSql() {
    return generatedSql;
  }

  public void setGeneratedSql(@jakarta.annotation.Nullable String generatedSql) {
    this.generatedSql = generatedSql;
  }


  public QueryResponse diagnostics(@jakarta.annotation.Nonnull List<QueryDiagnostic> diagnostics) {
    this.diagnostics = diagnostics;
    return this;
  }

  public QueryResponse addDiagnosticsItem(QueryDiagnostic diagnosticsItem) {
    if (this.diagnostics == null) {
      this.diagnostics = new ArrayList<>();
    }
    this.diagnostics.add(diagnosticsItem);
    return this;
  }

  /**
   * Get diagnostics
   * @return diagnostics
   */
  @jakarta.annotation.Nonnull
  public List<QueryDiagnostic> getDiagnostics() {
    return diagnostics;
  }

  public void setDiagnostics(@jakarta.annotation.Nonnull List<QueryDiagnostic> diagnostics) {
    this.diagnostics = diagnostics;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the QueryResponse instance itself
   */
  public QueryResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryResponse queryResponse = (QueryResponse) o;
    return Objects.equals(this.columns, queryResponse.columns) &&
        Objects.equals(this.rows, queryResponse.rows) &&
        Objects.equals(this.truncated, queryResponse.truncated) &&
        Objects.equals(this.elapsedMilliseconds, queryResponse.elapsedMilliseconds) &&
        Objects.equals(this.rowsAffected, queryResponse.rowsAffected) &&
        Objects.equals(this.language, queryResponse.language) &&
        Objects.equals(this.generatedSql, queryResponse.generatedSql) &&
        Objects.equals(this.diagnostics, queryResponse.diagnostics)&&
        Objects.equals(this.additionalProperties, queryResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columns, rows, truncated, elapsedMilliseconds, rowsAffected, language, generatedSql, diagnostics, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryResponse {\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    truncated: ").append(toIndentedString(truncated)).append("\n");
    sb.append("    elapsedMilliseconds: ").append(toIndentedString(elapsedMilliseconds)).append("\n");
    sb.append("    rowsAffected: ").append(toIndentedString(rowsAffected)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    generatedSql: ").append(toIndentedString(generatedSql)).append("\n");
    sb.append("    diagnostics: ").append(toIndentedString(diagnostics)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("columns", "rows", "truncated", "elapsedMilliseconds", "rowsAffected", "language", "generatedSql", "diagnostics"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("columns", "rows", "truncated", "elapsedMilliseconds", "rowsAffected", "language", "generatedSql", "diagnostics"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QueryResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QueryResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QueryResponse is not found in the empty JSON string", QueryResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : QueryResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("columns").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `columns` to be an array in the JSON string but got `%s`", jsonObj.get("columns").toString()));
      }

      JsonArray jsonArraycolumns = jsonObj.getAsJsonArray("columns");
      // validate the required field `columns` (array)
      for (int i = 0; i < jsonArraycolumns.size(); i++) {
        ColumnDto.validateJsonElement(jsonArraycolumns.get(i));
      };
      // ensure the required json array is present
      if (jsonObj.get("rows") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("rows").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `rows` to be an array in the JSON string but got `%s`", jsonObj.get("rows").toString()));
      }
      if (!jsonObj.get("language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("language").toString()));
      }
      if ((jsonObj.get("generatedSql") != null && !jsonObj.get("generatedSql").isJsonNull()) && !jsonObj.get("generatedSql").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `generatedSql` to be a primitive type in the JSON string but got `%s`", jsonObj.get("generatedSql").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("diagnostics").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `diagnostics` to be an array in the JSON string but got `%s`", jsonObj.get("diagnostics").toString()));
      }

      JsonArray jsonArraydiagnostics = jsonObj.getAsJsonArray("diagnostics");
      // validate the required field `diagnostics` (array)
      for (int i = 0; i < jsonArraydiagnostics.size(); i++) {
        QueryDiagnostic.validateJsonElement(jsonArraydiagnostics.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QueryResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QueryResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QueryResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QueryResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<QueryResponse>() {
           @Override
           public void write(JsonWriter out, QueryResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public QueryResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             QueryResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QueryResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QueryResponse
   * @throws IOException if the JSON string is invalid with respect to QueryResponse
   */
  public static QueryResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QueryResponse.class);
  }

  /**
   * Convert an instance of QueryResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

