/*
 * LakeHold Public API
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakehold.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lakehold.sdk.JSON;

/**
 * SnapshotDto
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SnapshotDto {
  public static final String SERIALIZED_NAME_SNAPSHOT_ID = "snapshotId";
  @SerializedName(SERIALIZED_NAME_SNAPSHOT_ID)
  @jakarta.annotation.Nonnull
  private Long snapshotId;

  public static final String SERIALIZED_NAME_COMMITTED_AT = "committedAt";
  @SerializedName(SERIALIZED_NAME_COMMITTED_AT)
  @jakarta.annotation.Nonnull
  private OffsetDateTime committedAt;

  public static final String SERIALIZED_NAME_SCHEMA_VERSION = "schemaVersion";
  @SerializedName(SERIALIZED_NAME_SCHEMA_VERSION)
  @jakarta.annotation.Nonnull
  private Long schemaVersion;

  public static final String SERIALIZED_NAME_COMMIT_MESSAGE = "commitMessage";
  @SerializedName(SERIALIZED_NAME_COMMIT_MESSAGE)
  @jakarta.annotation.Nullable
  private String commitMessage;

  public SnapshotDto() {
  }

  public SnapshotDto snapshotId(@jakarta.annotation.Nonnull Long snapshotId) {
    this.snapshotId = snapshotId;
    return this;
  }

  /**
   * Get snapshotId
   * @return snapshotId
   */
  @jakarta.annotation.Nonnull
  public Long getSnapshotId() {
    return snapshotId;
  }

  public void setSnapshotId(@jakarta.annotation.Nonnull Long snapshotId) {
    this.snapshotId = snapshotId;
  }


  public SnapshotDto committedAt(@jakarta.annotation.Nonnull OffsetDateTime committedAt) {
    this.committedAt = committedAt;
    return this;
  }

  /**
   * Get committedAt
   * @return committedAt
   */
  @jakarta.annotation.Nonnull
  public OffsetDateTime getCommittedAt() {
    return committedAt;
  }

  public void setCommittedAt(@jakarta.annotation.Nonnull OffsetDateTime committedAt) {
    this.committedAt = committedAt;
  }


  public SnapshotDto schemaVersion(@jakarta.annotation.Nonnull Long schemaVersion) {
    this.schemaVersion = schemaVersion;
    return this;
  }

  /**
   * Get schemaVersion
   * @return schemaVersion
   */
  @jakarta.annotation.Nonnull
  public Long getSchemaVersion() {
    return schemaVersion;
  }

  public void setSchemaVersion(@jakarta.annotation.Nonnull Long schemaVersion) {
    this.schemaVersion = schemaVersion;
  }


  public SnapshotDto commitMessage(@jakarta.annotation.Nullable String commitMessage) {
    this.commitMessage = commitMessage;
    return this;
  }

  /**
   * Get commitMessage
   * @return commitMessage
   */
  @jakarta.annotation.Nullable
  public String getCommitMessage() {
    return commitMessage;
  }

  public void setCommitMessage(@jakarta.annotation.Nullable String commitMessage) {
    this.commitMessage = commitMessage;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SnapshotDto instance itself
   */
  public SnapshotDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SnapshotDto snapshotDto = (SnapshotDto) o;
    return Objects.equals(this.snapshotId, snapshotDto.snapshotId) &&
        Objects.equals(this.committedAt, snapshotDto.committedAt) &&
        Objects.equals(this.schemaVersion, snapshotDto.schemaVersion) &&
        Objects.equals(this.commitMessage, snapshotDto.commitMessage)&&
        Objects.equals(this.additionalProperties, snapshotDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(snapshotId, committedAt, schemaVersion, commitMessage, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SnapshotDto {\n");
    sb.append("    snapshotId: ").append(toIndentedString(snapshotId)).append("\n");
    sb.append("    committedAt: ").append(toIndentedString(committedAt)).append("\n");
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    commitMessage: ").append(toIndentedString(commitMessage)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("snapshotId", "committedAt", "schemaVersion", "commitMessage"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("snapshotId", "committedAt", "schemaVersion", "commitMessage"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SnapshotDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SnapshotDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SnapshotDto is not found in the empty JSON string", SnapshotDto.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SnapshotDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("commitMessage") != null && !jsonObj.get("commitMessage").isJsonNull()) && !jsonObj.get("commitMessage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `commitMessage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("commitMessage").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SnapshotDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SnapshotDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SnapshotDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SnapshotDto.class));

       return (TypeAdapter<T>) new TypeAdapter<SnapshotDto>() {
           @Override
           public void write(JsonWriter out, SnapshotDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SnapshotDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SnapshotDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SnapshotDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SnapshotDto
   * @throws IOException if the JSON string is invalid with respect to SnapshotDto
   */
  public static SnapshotDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SnapshotDto.class);
  }

  /**
   * Convert an instance of SnapshotDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

