/*
 * LakeHold Public API
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakehold.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lakehold.sdk.JSON;

/**
 * StorageProfileSummaryDto
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class StorageProfileSummaryDto {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @jakarta.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  @jakarta.annotation.Nonnull
  private String kind;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  @jakarta.annotation.Nullable
  private String region;

  public static final String SERIALIZED_NAME_ENDPOINT = "endpoint";
  @SerializedName(SERIALIZED_NAME_ENDPOINT)
  @jakarta.annotation.Nullable
  private String endpoint;

  public static final String SERIALIZED_NAME_USE_SSL = "useSsl";
  @SerializedName(SERIALIZED_NAME_USE_SSL)
  @jakarta.annotation.Nonnull
  private Boolean useSsl;

  public static final String SERIALIZED_NAME_URL_STYLE = "urlStyle";
  @SerializedName(SERIALIZED_NAME_URL_STYLE)
  @jakarta.annotation.Nonnull
  private String urlStyle;

  public static final String SERIALIZED_NAME_CREDENTIALS_CONFIGURED = "credentialsConfigured";
  @SerializedName(SERIALIZED_NAME_CREDENTIALS_CONFIGURED)
  @jakarta.annotation.Nonnull
  private Boolean credentialsConfigured;

  public static final String SERIALIZED_NAME_AZURE_AUTHENTICATION = "azureAuthentication";
  @SerializedName(SERIALIZED_NAME_AZURE_AUTHENTICATION)
  @jakarta.annotation.Nullable
  private String azureAuthentication;

  public StorageProfileSummaryDto() {
  }

  public StorageProfileSummaryDto name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public StorageProfileSummaryDto kind(@jakarta.annotation.Nonnull String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @jakarta.annotation.Nonnull
  public String getKind() {
    return kind;
  }

  public void setKind(@jakarta.annotation.Nonnull String kind) {
    this.kind = kind;
  }


  public StorageProfileSummaryDto region(@jakarta.annotation.Nullable String region) {
    this.region = region;
    return this;
  }

  /**
   * Get region
   * @return region
   */
  @jakarta.annotation.Nullable
  public String getRegion() {
    return region;
  }

  public void setRegion(@jakarta.annotation.Nullable String region) {
    this.region = region;
  }


  public StorageProfileSummaryDto endpoint(@jakarta.annotation.Nullable String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

  /**
   * Get endpoint
   * @return endpoint
   */
  @jakarta.annotation.Nullable
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(@jakarta.annotation.Nullable String endpoint) {
    this.endpoint = endpoint;
  }


  public StorageProfileSummaryDto useSsl(@jakarta.annotation.Nonnull Boolean useSsl) {
    this.useSsl = useSsl;
    return this;
  }

  /**
   * Get useSsl
   * @return useSsl
   */
  @jakarta.annotation.Nonnull
  public Boolean getUseSsl() {
    return useSsl;
  }

  public void setUseSsl(@jakarta.annotation.Nonnull Boolean useSsl) {
    this.useSsl = useSsl;
  }


  public StorageProfileSummaryDto urlStyle(@jakarta.annotation.Nonnull String urlStyle) {
    this.urlStyle = urlStyle;
    return this;
  }

  /**
   * Get urlStyle
   * @return urlStyle
   */
  @jakarta.annotation.Nonnull
  public String getUrlStyle() {
    return urlStyle;
  }

  public void setUrlStyle(@jakarta.annotation.Nonnull String urlStyle) {
    this.urlStyle = urlStyle;
  }


  public StorageProfileSummaryDto credentialsConfigured(@jakarta.annotation.Nonnull Boolean credentialsConfigured) {
    this.credentialsConfigured = credentialsConfigured;
    return this;
  }

  /**
   * Get credentialsConfigured
   * @return credentialsConfigured
   */
  @jakarta.annotation.Nonnull
  public Boolean getCredentialsConfigured() {
    return credentialsConfigured;
  }

  public void setCredentialsConfigured(@jakarta.annotation.Nonnull Boolean credentialsConfigured) {
    this.credentialsConfigured = credentialsConfigured;
  }


  public StorageProfileSummaryDto azureAuthentication(@jakarta.annotation.Nullable String azureAuthentication) {
    this.azureAuthentication = azureAuthentication;
    return this;
  }

  /**
   * Get azureAuthentication
   * @return azureAuthentication
   */
  @jakarta.annotation.Nullable
  public String getAzureAuthentication() {
    return azureAuthentication;
  }

  public void setAzureAuthentication(@jakarta.annotation.Nullable String azureAuthentication) {
    this.azureAuthentication = azureAuthentication;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the StorageProfileSummaryDto instance itself
   */
  public StorageProfileSummaryDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StorageProfileSummaryDto storageProfileSummaryDto = (StorageProfileSummaryDto) o;
    return Objects.equals(this.name, storageProfileSummaryDto.name) &&
        Objects.equals(this.kind, storageProfileSummaryDto.kind) &&
        Objects.equals(this.region, storageProfileSummaryDto.region) &&
        Objects.equals(this.endpoint, storageProfileSummaryDto.endpoint) &&
        Objects.equals(this.useSsl, storageProfileSummaryDto.useSsl) &&
        Objects.equals(this.urlStyle, storageProfileSummaryDto.urlStyle) &&
        Objects.equals(this.credentialsConfigured, storageProfileSummaryDto.credentialsConfigured) &&
        Objects.equals(this.azureAuthentication, storageProfileSummaryDto.azureAuthentication)&&
        Objects.equals(this.additionalProperties, storageProfileSummaryDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, kind, region, endpoint, useSsl, urlStyle, credentialsConfigured, azureAuthentication, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StorageProfileSummaryDto {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    useSsl: ").append(toIndentedString(useSsl)).append("\n");
    sb.append("    urlStyle: ").append(toIndentedString(urlStyle)).append("\n");
    sb.append("    credentialsConfigured: ").append(toIndentedString(credentialsConfigured)).append("\n");
    sb.append("    azureAuthentication: ").append(toIndentedString(azureAuthentication)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "kind", "region", "endpoint", "useSsl", "urlStyle", "credentialsConfigured", "azureAuthentication"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "kind", "region", "endpoint", "useSsl", "urlStyle", "credentialsConfigured", "azureAuthentication"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StorageProfileSummaryDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StorageProfileSummaryDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StorageProfileSummaryDto is not found in the empty JSON string", StorageProfileSummaryDto.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StorageProfileSummaryDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("kind").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kind` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kind").toString()));
      }
      if ((jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull()) && !jsonObj.get("region").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
      }
      if ((jsonObj.get("endpoint") != null && !jsonObj.get("endpoint").isJsonNull()) && !jsonObj.get("endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endpoint").toString()));
      }
      if (!jsonObj.get("urlStyle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `urlStyle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("urlStyle").toString()));
      }
      if ((jsonObj.get("azureAuthentication") != null && !jsonObj.get("azureAuthentication").isJsonNull()) && !jsonObj.get("azureAuthentication").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azureAuthentication` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azureAuthentication").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StorageProfileSummaryDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StorageProfileSummaryDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StorageProfileSummaryDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StorageProfileSummaryDto.class));

       return (TypeAdapter<T>) new TypeAdapter<StorageProfileSummaryDto>() {
           @Override
           public void write(JsonWriter out, StorageProfileSummaryDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public StorageProfileSummaryDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             StorageProfileSummaryDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StorageProfileSummaryDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StorageProfileSummaryDto
   * @throws IOException if the JSON string is invalid with respect to StorageProfileSummaryDto
   */
  public static StorageProfileSummaryDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StorageProfileSummaryDto.class);
  }

  /**
   * Convert an instance of StorageProfileSummaryDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

