/*
 * LakeHold Public API
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakehold.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.lakehold.sdk.JSON;

/**
 * SubscriptionDto
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SubscriptionDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @jakarta.annotation.Nonnull
  private Integer id;

  public static final String SERIALIZED_NAME_CATALOG = "catalog";
  @SerializedName(SERIALIZED_NAME_CATALOG)
  @jakarta.annotation.Nonnull
  private String catalog;

  public static final String SERIALIZED_NAME_SCHEMA = "schema";
  @SerializedName(SERIALIZED_NAME_SCHEMA)
  @jakarta.annotation.Nonnull
  private String schema;

  public static final String SERIALIZED_NAME_TABLE = "table";
  @SerializedName(SERIALIZED_NAME_TABLE)
  @jakarta.annotation.Nullable
  private String table;

  public static final String SERIALIZED_NAME_ENDPOINT_URL = "endpointUrl";
  @SerializedName(SERIALIZED_NAME_ENDPOINT_URL)
  @jakarta.annotation.Nonnull
  private String endpointUrl;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  @jakarta.annotation.Nonnull
  private Boolean active;

  public static final String SERIALIZED_NAME_LAST_DELIVERED_SNAPSHOT = "lastDeliveredSnapshot";
  @SerializedName(SERIALIZED_NAME_LAST_DELIVERED_SNAPSHOT)
  @jakarta.annotation.Nonnull
  private Long lastDeliveredSnapshot;

  public static final String SERIALIZED_NAME_CONSECUTIVE_FAILURES = "consecutiveFailures";
  @SerializedName(SERIALIZED_NAME_CONSECUTIVE_FAILURES)
  @jakarta.annotation.Nonnull
  private Integer consecutiveFailures;

  public static final String SERIALIZED_NAME_LAST_ATTEMPT_UTC = "lastAttemptUtc";
  @SerializedName(SERIALIZED_NAME_LAST_ATTEMPT_UTC)
  @jakarta.annotation.Nullable
  private OffsetDateTime lastAttemptUtc;

  public static final String SERIALIZED_NAME_LAST_ERROR = "lastError";
  @SerializedName(SERIALIZED_NAME_LAST_ERROR)
  @jakarta.annotation.Nullable
  private String lastError;

  public static final String SERIALIZED_NAME_CREATED_UTC = "createdUtc";
  @SerializedName(SERIALIZED_NAME_CREATED_UTC)
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdUtc;

  public SubscriptionDto() {
  }

  public SubscriptionDto id(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  public Integer getId() {
    return id;
  }

  public void setId(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public SubscriptionDto catalog(@jakarta.annotation.Nonnull String catalog) {
    this.catalog = catalog;
    return this;
  }

  /**
   * Get catalog
   * @return catalog
   */
  @jakarta.annotation.Nonnull
  public String getCatalog() {
    return catalog;
  }

  public void setCatalog(@jakarta.annotation.Nonnull String catalog) {
    this.catalog = catalog;
  }


  public SubscriptionDto schema(@jakarta.annotation.Nonnull String schema) {
    this.schema = schema;
    return this;
  }

  /**
   * Get schema
   * @return schema
   */
  @jakarta.annotation.Nonnull
  public String getSchema() {
    return schema;
  }

  public void setSchema(@jakarta.annotation.Nonnull String schema) {
    this.schema = schema;
  }


  public SubscriptionDto table(@jakarta.annotation.Nullable String table) {
    this.table = table;
    return this;
  }

  /**
   * Get table
   * @return table
   */
  @jakarta.annotation.Nullable
  public String getTable() {
    return table;
  }

  public void setTable(@jakarta.annotation.Nullable String table) {
    this.table = table;
  }


  public SubscriptionDto endpointUrl(@jakarta.annotation.Nonnull String endpointUrl) {
    this.endpointUrl = endpointUrl;
    return this;
  }

  /**
   * Get endpointUrl
   * @return endpointUrl
   */
  @jakarta.annotation.Nonnull
  public String getEndpointUrl() {
    return endpointUrl;
  }

  public void setEndpointUrl(@jakarta.annotation.Nonnull String endpointUrl) {
    this.endpointUrl = endpointUrl;
  }


  public SubscriptionDto active(@jakarta.annotation.Nonnull Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @jakarta.annotation.Nonnull
  public Boolean getActive() {
    return active;
  }

  public void setActive(@jakarta.annotation.Nonnull Boolean active) {
    this.active = active;
  }


  public SubscriptionDto lastDeliveredSnapshot(@jakarta.annotation.Nonnull Long lastDeliveredSnapshot) {
    this.lastDeliveredSnapshot = lastDeliveredSnapshot;
    return this;
  }

  /**
   * Get lastDeliveredSnapshot
   * @return lastDeliveredSnapshot
   */
  @jakarta.annotation.Nonnull
  public Long getLastDeliveredSnapshot() {
    return lastDeliveredSnapshot;
  }

  public void setLastDeliveredSnapshot(@jakarta.annotation.Nonnull Long lastDeliveredSnapshot) {
    this.lastDeliveredSnapshot = lastDeliveredSnapshot;
  }


  public SubscriptionDto consecutiveFailures(@jakarta.annotation.Nonnull Integer consecutiveFailures) {
    this.consecutiveFailures = consecutiveFailures;
    return this;
  }

  /**
   * Get consecutiveFailures
   * @return consecutiveFailures
   */
  @jakarta.annotation.Nonnull
  public Integer getConsecutiveFailures() {
    return consecutiveFailures;
  }

  public void setConsecutiveFailures(@jakarta.annotation.Nonnull Integer consecutiveFailures) {
    this.consecutiveFailures = consecutiveFailures;
  }


  public SubscriptionDto lastAttemptUtc(@jakarta.annotation.Nullable OffsetDateTime lastAttemptUtc) {
    this.lastAttemptUtc = lastAttemptUtc;
    return this;
  }

  /**
   * Get lastAttemptUtc
   * @return lastAttemptUtc
   */
  @jakarta.annotation.Nullable
  public OffsetDateTime getLastAttemptUtc() {
    return lastAttemptUtc;
  }

  public void setLastAttemptUtc(@jakarta.annotation.Nullable OffsetDateTime lastAttemptUtc) {
    this.lastAttemptUtc = lastAttemptUtc;
  }


  public SubscriptionDto lastError(@jakarta.annotation.Nullable String lastError) {
    this.lastError = lastError;
    return this;
  }

  /**
   * Get lastError
   * @return lastError
   */
  @jakarta.annotation.Nullable
  public String getLastError() {
    return lastError;
  }

  public void setLastError(@jakarta.annotation.Nullable String lastError) {
    this.lastError = lastError;
  }


  public SubscriptionDto createdUtc(@jakarta.annotation.Nonnull OffsetDateTime createdUtc) {
    this.createdUtc = createdUtc;
    return this;
  }

  /**
   * Get createdUtc
   * @return createdUtc
   */
  @jakarta.annotation.Nonnull
  public OffsetDateTime getCreatedUtc() {
    return createdUtc;
  }

  public void setCreatedUtc(@jakarta.annotation.Nonnull OffsetDateTime createdUtc) {
    this.createdUtc = createdUtc;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SubscriptionDto instance itself
   */
  public SubscriptionDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionDto subscriptionDto = (SubscriptionDto) o;
    return Objects.equals(this.id, subscriptionDto.id) &&
        Objects.equals(this.catalog, subscriptionDto.catalog) &&
        Objects.equals(this.schema, subscriptionDto.schema) &&
        Objects.equals(this.table, subscriptionDto.table) &&
        Objects.equals(this.endpointUrl, subscriptionDto.endpointUrl) &&
        Objects.equals(this.active, subscriptionDto.active) &&
        Objects.equals(this.lastDeliveredSnapshot, subscriptionDto.lastDeliveredSnapshot) &&
        Objects.equals(this.consecutiveFailures, subscriptionDto.consecutiveFailures) &&
        Objects.equals(this.lastAttemptUtc, subscriptionDto.lastAttemptUtc) &&
        Objects.equals(this.lastError, subscriptionDto.lastError) &&
        Objects.equals(this.createdUtc, subscriptionDto.createdUtc)&&
        Objects.equals(this.additionalProperties, subscriptionDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, catalog, schema, table, endpointUrl, active, lastDeliveredSnapshot, consecutiveFailures, lastAttemptUtc, lastError, createdUtc, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    catalog: ").append(toIndentedString(catalog)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    table: ").append(toIndentedString(table)).append("\n");
    sb.append("    endpointUrl: ").append(toIndentedString(endpointUrl)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    lastDeliveredSnapshot: ").append(toIndentedString(lastDeliveredSnapshot)).append("\n");
    sb.append("    consecutiveFailures: ").append(toIndentedString(consecutiveFailures)).append("\n");
    sb.append("    lastAttemptUtc: ").append(toIndentedString(lastAttemptUtc)).append("\n");
    sb.append("    lastError: ").append(toIndentedString(lastError)).append("\n");
    sb.append("    createdUtc: ").append(toIndentedString(createdUtc)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "catalog", "schema", "table", "endpointUrl", "active", "lastDeliveredSnapshot", "consecutiveFailures", "lastAttemptUtc", "lastError", "createdUtc"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "catalog", "schema", "table", "endpointUrl", "active", "lastDeliveredSnapshot", "consecutiveFailures", "lastAttemptUtc", "lastError", "createdUtc"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubscriptionDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubscriptionDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubscriptionDto is not found in the empty JSON string", SubscriptionDto.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubscriptionDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("catalog").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `catalog` to be a primitive type in the JSON string but got `%s`", jsonObj.get("catalog").toString()));
      }
      if (!jsonObj.get("schema").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `schema` to be a primitive type in the JSON string but got `%s`", jsonObj.get("schema").toString()));
      }
      if ((jsonObj.get("table") != null && !jsonObj.get("table").isJsonNull()) && !jsonObj.get("table").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `table` to be a primitive type in the JSON string but got `%s`", jsonObj.get("table").toString()));
      }
      if (!jsonObj.get("endpointUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endpointUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endpointUrl").toString()));
      }
      if ((jsonObj.get("lastError") != null && !jsonObj.get("lastError").isJsonNull()) && !jsonObj.get("lastError").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastError` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastError").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubscriptionDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubscriptionDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubscriptionDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubscriptionDto.class));

       return (TypeAdapter<T>) new TypeAdapter<SubscriptionDto>() {
           @Override
           public void write(JsonWriter out, SubscriptionDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SubscriptionDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SubscriptionDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubscriptionDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubscriptionDto
   * @throws IOException if the JSON string is invalid with respect to SubscriptionDto
   */
  public static SubscriptionDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubscriptionDto.class);
  }

  /**
   * Convert an instance of SubscriptionDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

