/*
 * LakeHold Public API
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakehold.sdk.api;

import io.lakehold.sdk.ApiCallback;
import io.lakehold.sdk.ApiClient;
import io.lakehold.sdk.ApiException;
import io.lakehold.sdk.ApiResponse;
import io.lakehold.sdk.Configuration;
import io.lakehold.sdk.Pair;
import io.lakehold.sdk.ProgressRequestBody;
import io.lakehold.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.lakehold.sdk.model.PublicApiCapabilities;
import io.lakehold.sdk.model.PublicApiProblemDetails;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DiscoveryApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DiscoveryApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DiscoveryApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getApiCapabilitiesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/capabilities";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/problem+json",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getApiCapabilitiesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getApiCapabilitiesCall(_callback);

    }


    private ApiResponse<PublicApiCapabilities> getApiCapabilitiesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getApiCapabilitiesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<PublicApiCapabilities>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getApiCapabilitiesAsync(final ApiCallback<PublicApiCapabilities> _callback) throws ApiException {

        okhttp3.Call localVarCall = getApiCapabilitiesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<PublicApiCapabilities>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class APIgetApiCapabilitiesRequest {

        private APIgetApiCapabilitiesRequest() {
        }

        /**
         * Build call for getApiCapabilities
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table border="1">
       <caption>Response Details</caption>
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 401 </td><td> Unauthorized </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 404 </td><td> Not Found </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 408 </td><td> Request Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 409 </td><td> Conflict </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 412 </td><td> Precondition Failed </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 413 </td><td> Payload Too Large </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 422 </td><td> Unprocessable Entity </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 429 </td><td> Too Many Requests </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 500 </td><td> Internal Server Error </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 502 </td><td> Bad Gateway </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 503 </td><td> Service Unavailable </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 504 </td><td> Gateway Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getApiCapabilitiesCall(_callback);
        }

        /**
         * Execute getApiCapabilities request
         * @return PublicApiCapabilities
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table border="1">
       <caption>Response Details</caption>
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 401 </td><td> Unauthorized </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 404 </td><td> Not Found </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 408 </td><td> Request Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 409 </td><td> Conflict </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 412 </td><td> Precondition Failed </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 413 </td><td> Payload Too Large </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 422 </td><td> Unprocessable Entity </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 429 </td><td> Too Many Requests </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 500 </td><td> Internal Server Error </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 502 </td><td> Bad Gateway </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 503 </td><td> Service Unavailable </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 504 </td><td> Gateway Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
         </table>
         */
        public PublicApiCapabilities execute() throws ApiException {
            ApiResponse<PublicApiCapabilities> localVarResp = getApiCapabilitiesWithHttpInfo();
            return localVarResp.getData();
        }

        /**
         * Execute getApiCapabilities request with HTTP info returned
         * @return ApiResponse&lt;PublicApiCapabilities&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table border="1">
       <caption>Response Details</caption>
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 401 </td><td> Unauthorized </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 404 </td><td> Not Found </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 408 </td><td> Request Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 409 </td><td> Conflict </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 412 </td><td> Precondition Failed </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 413 </td><td> Payload Too Large </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 422 </td><td> Unprocessable Entity </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 429 </td><td> Too Many Requests </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 500 </td><td> Internal Server Error </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 502 </td><td> Bad Gateway </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 503 </td><td> Service Unavailable </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 504 </td><td> Gateway Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
         </table>
         */
        public ApiResponse<PublicApiCapabilities> executeWithHttpInfo() throws ApiException {
            return getApiCapabilitiesWithHttpInfo();
        }

        /**
         * Execute getApiCapabilities request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table border="1">
       <caption>Response Details</caption>
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 401 </td><td> Unauthorized </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 404 </td><td> Not Found </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 408 </td><td> Request Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 409 </td><td> Conflict </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 412 </td><td> Precondition Failed </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 413 </td><td> Payload Too Large </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 422 </td><td> Unprocessable Entity </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 429 </td><td> Too Many Requests </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 500 </td><td> Internal Server Error </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 502 </td><td> Bad Gateway </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 503 </td><td> Service Unavailable </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 504 </td><td> Gateway Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<PublicApiCapabilities> _callback) throws ApiException {
            return getApiCapabilitiesAsync(_callback);
        }
    }

    /**
     * Returns the public API version and optional capabilities supported by this server.
     * 
     * @return APIgetApiCapabilitiesRequest
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 408 </td><td> Request Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 409 </td><td> Conflict </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 412 </td><td> Precondition Failed </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 413 </td><td> Payload Too Large </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 422 </td><td> Unprocessable Entity </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 429 </td><td> Too Many Requests </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 502 </td><td> Bad Gateway </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * X-Request-Id - Server correlation identifier for support and diagnostics. <br>  </td></tr>
     </table>
     */
    public APIgetApiCapabilitiesRequest getApiCapabilities() {
        return new APIgetApiCapabilitiesRequest();
    }
}
