// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// BackupGenerationDto
    /// </summary>
    public partial class BackupGenerationDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackupGenerationDto" /> class.
        /// </summary>
        /// <param name="generation">generation</param>
        /// <param name="tableCount">tableCount</param>
        /// <param name="complete">complete</param>
        /// <param name="createdUtc">createdUtc</param>
        /// <param name="snapshotId">snapshotId</param>
        [JsonConstructor]
        public BackupGenerationDto(string generation, int tableCount, bool complete, DateTime? createdUtc = default, long? snapshotId = default)
        {
            Generation = generation;
            TableCount = tableCount;
            Complete = complete;
            CreatedUtc = createdUtc;
            SnapshotId = snapshotId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Generation
        /// </summary>
        [JsonPropertyName("generation")]
        public string Generation { get; set; }

        /// <summary>
        /// Gets or Sets TableCount
        /// </summary>
        [JsonPropertyName("tableCount")]
        public int TableCount { get; set; }

        /// <summary>
        /// Gets or Sets Complete
        /// </summary>
        [JsonPropertyName("complete")]
        public bool Complete { get; set; }

        /// <summary>
        /// Gets or Sets CreatedUtc
        /// </summary>
        [JsonPropertyName("createdUtc")]
        public DateTime? CreatedUtc { get; set; }

        /// <summary>
        /// Gets or Sets SnapshotId
        /// </summary>
        [JsonPropertyName("snapshotId")]
        public long? SnapshotId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BackupGenerationDto {\n");
            sb.Append("  Generation: ").Append(Generation).Append("\n");
            sb.Append("  TableCount: ").Append(TableCount).Append("\n");
            sb.Append("  Complete: ").Append(Complete).Append("\n");
            sb.Append("  CreatedUtc: ").Append(CreatedUtc).Append("\n");
            sb.Append("  SnapshotId: ").Append(SnapshotId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BackupGenerationDto" />
    /// </summary>
    public class BackupGenerationDtoJsonConverter : JsonConverter<BackupGenerationDto>
    {
        /// <summary>
        /// The format to use to serialize CreatedUtc
        /// </summary>
        public static string CreatedUtcFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="BackupGenerationDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BackupGenerationDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> generation = default;
            Option<int?> tableCount = default;
            Option<bool?> complete = default;
            Option<DateTime?> createdUtc = default;
            Option<long?> snapshotId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "generation":
                            generation = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tableCount":
                            tableCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "complete":
                            complete = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "createdUtc":
                            createdUtc = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "snapshotId":
                            snapshotId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!generation.IsSet)
                throw new ArgumentException("Property is required for class BackupGenerationDto.", nameof(generation));

            if (!tableCount.IsSet)
                throw new ArgumentException("Property is required for class BackupGenerationDto.", nameof(tableCount));

            if (!complete.IsSet)
                throw new ArgumentException("Property is required for class BackupGenerationDto.", nameof(complete));

            if (!createdUtc.IsSet)
                throw new ArgumentException("Property is required for class BackupGenerationDto.", nameof(createdUtc));

            if (!snapshotId.IsSet)
                throw new ArgumentException("Property is required for class BackupGenerationDto.", nameof(snapshotId));

            if (generation.IsSet && generation.Value == null)
                throw new ArgumentNullException(nameof(generation), "Property is not nullable for class BackupGenerationDto.");

            if (tableCount.IsSet && tableCount.Value == null)
                throw new ArgumentNullException(nameof(tableCount), "Property is not nullable for class BackupGenerationDto.");

            if (complete.IsSet && complete.Value == null)
                throw new ArgumentNullException(nameof(complete), "Property is not nullable for class BackupGenerationDto.");

            return new BackupGenerationDto(generation.Value!, tableCount.Value!.Value!, complete.Value!.Value!, createdUtc.Value!, snapshotId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BackupGenerationDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="backupGenerationDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, BackupGenerationDto backupGenerationDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, backupGenerationDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BackupGenerationDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="backupGenerationDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, BackupGenerationDto backupGenerationDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (backupGenerationDto.Generation == null)
                throw new ArgumentNullException(nameof(backupGenerationDto.Generation), "Property is required for class BackupGenerationDto.");

            writer.WriteString("generation", backupGenerationDto.Generation);

            writer.WriteNumber("tableCount", backupGenerationDto.TableCount);

            writer.WriteBoolean("complete", backupGenerationDto.Complete);

            if (backupGenerationDto.CreatedUtc != null)
                writer.WriteString("createdUtc", backupGenerationDto.CreatedUtc.Value.ToString(CreatedUtcFormat));
            else
                writer.WriteNull("createdUtc");

            if (backupGenerationDto.SnapshotId != null)
                writer.WriteNumber("snapshotId", backupGenerationDto.SnapshotId.Value);
            else
                writer.WriteNull("snapshotId");
        }
    }
}
