// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// CreateSavedQueryRequest
    /// </summary>
    public partial class CreateSavedQueryRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSavedQueryRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="sql">sql</param>
        /// <param name="description">description</param>
        /// <param name="language">language (default to &quot;sql&quot;)</param>
        [JsonConstructor]
        public CreateSavedQueryRequest(string name, string sql, string? description = default, Option<string?> language = default)
        {
            Name = name;
            Sql = sql;
            Description = description;
            LanguageOption = language;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Sql
        /// </summary>
        [JsonPropertyName("sql")]
        public string Sql { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Used to track the state of Language
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LanguageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [JsonPropertyName("language")]
        public string? Language { get { return this.LanguageOption; } set { this.LanguageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateSavedQueryRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Sql: ").Append(Sql).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateSavedQueryRequest" />
    /// </summary>
    public class CreateSavedQueryRequestJsonConverter : JsonConverter<CreateSavedQueryRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateSavedQueryRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateSavedQueryRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> sql = default;
            Option<string?> description = default;
            Option<string?> language = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sql":
                            sql = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "language":
                            language = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateSavedQueryRequest.", nameof(name));

            if (!sql.IsSet)
                throw new ArgumentException("Property is required for class CreateSavedQueryRequest.", nameof(sql));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class CreateSavedQueryRequest.", nameof(description));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateSavedQueryRequest.");

            if (sql.IsSet && sql.Value == null)
                throw new ArgumentNullException(nameof(sql), "Property is not nullable for class CreateSavedQueryRequest.");

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class CreateSavedQueryRequest.");

            return new CreateSavedQueryRequest(name.Value!, sql.Value!, description.Value!, language);
        }

        /// <summary>
        /// Serializes a <see cref="CreateSavedQueryRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createSavedQueryRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, CreateSavedQueryRequest createSavedQueryRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createSavedQueryRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateSavedQueryRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createSavedQueryRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, CreateSavedQueryRequest createSavedQueryRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createSavedQueryRequest.Name == null)
                throw new ArgumentNullException(nameof(createSavedQueryRequest.Name), "Property is required for class CreateSavedQueryRequest.");

            if (createSavedQueryRequest.Sql == null)
                throw new ArgumentNullException(nameof(createSavedQueryRequest.Sql), "Property is required for class CreateSavedQueryRequest.");

            if (createSavedQueryRequest.LanguageOption.IsSet && createSavedQueryRequest.Language == null)
                throw new ArgumentNullException(nameof(createSavedQueryRequest.Language), "Property is required for class CreateSavedQueryRequest.");

            writer.WriteString("name", createSavedQueryRequest.Name);

            writer.WriteString("sql", createSavedQueryRequest.Sql);

            if (createSavedQueryRequest.Description != null)
                writer.WriteString("description", createSavedQueryRequest.Description);
            else
                writer.WriteNull("description");

            if (createSavedQueryRequest.LanguageOption.IsSet)
                writer.WriteString("language", createSavedQueryRequest.Language);
        }
    }
}
