// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// CursorPageOfSubscriptionDto
    /// </summary>
    public partial class CursorPageOfSubscriptionDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CursorPageOfSubscriptionDto" /> class.
        /// </summary>
        /// <param name="items">items</param>
        /// <param name="nextCursor">nextCursor</param>
        [JsonConstructor]
        public CursorPageOfSubscriptionDto(List<SubscriptionDto> items, string? nextCursor = default)
        {
            Items = items;
            NextCursor = nextCursor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonPropertyName("items")]
        public List<SubscriptionDto> Items { get; set; }

        /// <summary>
        /// Gets or Sets NextCursor
        /// </summary>
        [JsonPropertyName("nextCursor")]
        public string? NextCursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CursorPageOfSubscriptionDto {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CursorPageOfSubscriptionDto" />
    /// </summary>
    public class CursorPageOfSubscriptionDtoJsonConverter : JsonConverter<CursorPageOfSubscriptionDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="CursorPageOfSubscriptionDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CursorPageOfSubscriptionDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<SubscriptionDto>?> items = default;
            Option<string?> nextCursor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "items":
                            items = new Option<List<SubscriptionDto>?>(JsonSerializer.Deserialize<List<SubscriptionDto>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "nextCursor":
                            nextCursor = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!items.IsSet)
                throw new ArgumentException("Property is required for class CursorPageOfSubscriptionDto.", nameof(items));

            if (!nextCursor.IsSet)
                throw new ArgumentException("Property is required for class CursorPageOfSubscriptionDto.", nameof(nextCursor));

            if (items.IsSet && items.Value == null)
                throw new ArgumentNullException(nameof(items), "Property is not nullable for class CursorPageOfSubscriptionDto.");

            return new CursorPageOfSubscriptionDto(items.Value!, nextCursor.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CursorPageOfSubscriptionDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cursorPageOfSubscriptionDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, CursorPageOfSubscriptionDto cursorPageOfSubscriptionDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, cursorPageOfSubscriptionDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CursorPageOfSubscriptionDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cursorPageOfSubscriptionDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, CursorPageOfSubscriptionDto cursorPageOfSubscriptionDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (cursorPageOfSubscriptionDto.Items == null)
                throw new ArgumentNullException(nameof(cursorPageOfSubscriptionDto.Items), "Property is required for class CursorPageOfSubscriptionDto.");

            writer.WritePropertyName("items");
            JsonSerializer.Serialize(writer, cursorPageOfSubscriptionDto.Items, jsonSerializerOptions);
            if (cursorPageOfSubscriptionDto.NextCursor != null)
                writer.WriteString("nextCursor", cursorPageOfSubscriptionDto.NextCursor);
            else
                writer.WriteNull("nextCursor");
        }
    }
}
