// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// DataConnectorRunDto
    /// </summary>
    public partial class DataConnectorRunDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataConnectorRunDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="trigger">trigger</param>
        /// <param name="status">status</param>
        /// <param name="startedUtc">startedUtc</param>
        /// <param name="rowsRead">rowsRead</param>
        /// <param name="rowsPublished">rowsPublished</param>
        /// <param name="completedUtc">completedUtc</param>
        /// <param name="qualityPassed">qualityPassed</param>
        /// <param name="sourceVersion">sourceVersion</param>
        /// <param name="inputCheckpoint">inputCheckpoint</param>
        /// <param name="proposedCheckpoint">proposedCheckpoint</param>
        /// <param name="replayKey">replayKey</param>
        /// <param name="error">error</param>
        [JsonConstructor]
        public DataConnectorRunDto(int id, string trigger, string status, DateTime startedUtc, long rowsRead, long rowsPublished, DateTime? completedUtc = default, bool? qualityPassed = default, string? sourceVersion = default, string? inputCheckpoint = default, string? proposedCheckpoint = default, string? replayKey = default, string? error = default)
        {
            Id = id;
            Trigger = trigger;
            Status = status;
            StartedUtc = startedUtc;
            RowsRead = rowsRead;
            RowsPublished = rowsPublished;
            CompletedUtc = completedUtc;
            QualityPassed = qualityPassed;
            SourceVersion = sourceVersion;
            InputCheckpoint = inputCheckpoint;
            ProposedCheckpoint = proposedCheckpoint;
            ReplayKey = replayKey;
            Error = error;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Trigger
        /// </summary>
        [JsonPropertyName("trigger")]
        public string Trigger { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets StartedUtc
        /// </summary>
        [JsonPropertyName("startedUtc")]
        public DateTime StartedUtc { get; set; }

        /// <summary>
        /// Gets or Sets RowsRead
        /// </summary>
        [JsonPropertyName("rowsRead")]
        public long RowsRead { get; set; }

        /// <summary>
        /// Gets or Sets RowsPublished
        /// </summary>
        [JsonPropertyName("rowsPublished")]
        public long RowsPublished { get; set; }

        /// <summary>
        /// Gets or Sets CompletedUtc
        /// </summary>
        [JsonPropertyName("completedUtc")]
        public DateTime? CompletedUtc { get; set; }

        /// <summary>
        /// Gets or Sets QualityPassed
        /// </summary>
        [JsonPropertyName("qualityPassed")]
        public bool? QualityPassed { get; set; }

        /// <summary>
        /// Gets or Sets SourceVersion
        /// </summary>
        [JsonPropertyName("sourceVersion")]
        public string? SourceVersion { get; set; }

        /// <summary>
        /// Gets or Sets InputCheckpoint
        /// </summary>
        [JsonPropertyName("inputCheckpoint")]
        public string? InputCheckpoint { get; set; }

        /// <summary>
        /// Gets or Sets ProposedCheckpoint
        /// </summary>
        [JsonPropertyName("proposedCheckpoint")]
        public string? ProposedCheckpoint { get; set; }

        /// <summary>
        /// Gets or Sets ReplayKey
        /// </summary>
        [JsonPropertyName("replayKey")]
        public string? ReplayKey { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public string? Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataConnectorRunDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Trigger: ").Append(Trigger).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StartedUtc: ").Append(StartedUtc).Append("\n");
            sb.Append("  RowsRead: ").Append(RowsRead).Append("\n");
            sb.Append("  RowsPublished: ").Append(RowsPublished).Append("\n");
            sb.Append("  CompletedUtc: ").Append(CompletedUtc).Append("\n");
            sb.Append("  QualityPassed: ").Append(QualityPassed).Append("\n");
            sb.Append("  SourceVersion: ").Append(SourceVersion).Append("\n");
            sb.Append("  InputCheckpoint: ").Append(InputCheckpoint).Append("\n");
            sb.Append("  ProposedCheckpoint: ").Append(ProposedCheckpoint).Append("\n");
            sb.Append("  ReplayKey: ").Append(ReplayKey).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DataConnectorRunDto" />
    /// </summary>
    public class DataConnectorRunDtoJsonConverter : JsonConverter<DataConnectorRunDto>
    {
        /// <summary>
        /// The format to use to serialize StartedUtc
        /// </summary>
        public static string StartedUtcFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedUtc
        /// </summary>
        public static string CompletedUtcFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="DataConnectorRunDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DataConnectorRunDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> trigger = default;
            Option<string?> status = default;
            Option<DateTime?> startedUtc = default;
            Option<long?> rowsRead = default;
            Option<long?> rowsPublished = default;
            Option<DateTime?> completedUtc = default;
            Option<bool?> qualityPassed = default;
            Option<string?> sourceVersion = default;
            Option<string?> inputCheckpoint = default;
            Option<string?> proposedCheckpoint = default;
            Option<string?> replayKey = default;
            Option<string?> error = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "trigger":
                            trigger = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "startedUtc":
                            startedUtc = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "rowsRead":
                            rowsRead = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "rowsPublished":
                            rowsPublished = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "completedUtc":
                            completedUtc = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "qualityPassed":
                            qualityPassed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "sourceVersion":
                            sourceVersion = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "inputCheckpoint":
                            inputCheckpoint = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "proposedCheckpoint":
                            proposedCheckpoint = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "replayKey":
                            replayKey = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(id));

            if (!trigger.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(trigger));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(status));

            if (!startedUtc.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(startedUtc));

            if (!rowsRead.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(rowsRead));

            if (!rowsPublished.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(rowsPublished));

            if (!completedUtc.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(completedUtc));

            if (!qualityPassed.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(qualityPassed));

            if (!sourceVersion.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(sourceVersion));

            if (!inputCheckpoint.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(inputCheckpoint));

            if (!proposedCheckpoint.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(proposedCheckpoint));

            if (!replayKey.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(replayKey));

            if (!error.IsSet)
                throw new ArgumentException("Property is required for class DataConnectorRunDto.", nameof(error));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class DataConnectorRunDto.");

            if (trigger.IsSet && trigger.Value == null)
                throw new ArgumentNullException(nameof(trigger), "Property is not nullable for class DataConnectorRunDto.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class DataConnectorRunDto.");

            if (startedUtc.IsSet && startedUtc.Value == null)
                throw new ArgumentNullException(nameof(startedUtc), "Property is not nullable for class DataConnectorRunDto.");

            if (rowsRead.IsSet && rowsRead.Value == null)
                throw new ArgumentNullException(nameof(rowsRead), "Property is not nullable for class DataConnectorRunDto.");

            if (rowsPublished.IsSet && rowsPublished.Value == null)
                throw new ArgumentNullException(nameof(rowsPublished), "Property is not nullable for class DataConnectorRunDto.");

            return new DataConnectorRunDto(id.Value!.Value!, trigger.Value!, status.Value!, startedUtc.Value!.Value!, rowsRead.Value!.Value!, rowsPublished.Value!.Value!, completedUtc.Value!, qualityPassed.Value!, sourceVersion.Value!, inputCheckpoint.Value!, proposedCheckpoint.Value!, replayKey.Value!, error.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DataConnectorRunDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataConnectorRunDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, DataConnectorRunDto dataConnectorRunDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dataConnectorRunDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DataConnectorRunDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataConnectorRunDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, DataConnectorRunDto dataConnectorRunDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dataConnectorRunDto.Trigger == null)
                throw new ArgumentNullException(nameof(dataConnectorRunDto.Trigger), "Property is required for class DataConnectorRunDto.");

            if (dataConnectorRunDto.Status == null)
                throw new ArgumentNullException(nameof(dataConnectorRunDto.Status), "Property is required for class DataConnectorRunDto.");

            writer.WriteNumber("id", dataConnectorRunDto.Id);

            writer.WriteString("trigger", dataConnectorRunDto.Trigger);

            writer.WriteString("status", dataConnectorRunDto.Status);

            writer.WriteString("startedUtc", dataConnectorRunDto.StartedUtc.ToString(StartedUtcFormat));

            writer.WriteNumber("rowsRead", dataConnectorRunDto.RowsRead);

            writer.WriteNumber("rowsPublished", dataConnectorRunDto.RowsPublished);

            if (dataConnectorRunDto.CompletedUtc != null)
                writer.WriteString("completedUtc", dataConnectorRunDto.CompletedUtc.Value.ToString(CompletedUtcFormat));
            else
                writer.WriteNull("completedUtc");

            if (dataConnectorRunDto.QualityPassed != null)
                writer.WriteBoolean("qualityPassed", dataConnectorRunDto.QualityPassed.Value);
            else
                writer.WriteNull("qualityPassed");

            if (dataConnectorRunDto.SourceVersion != null)
                writer.WriteString("sourceVersion", dataConnectorRunDto.SourceVersion);
            else
                writer.WriteNull("sourceVersion");

            if (dataConnectorRunDto.InputCheckpoint != null)
                writer.WriteString("inputCheckpoint", dataConnectorRunDto.InputCheckpoint);
            else
                writer.WriteNull("inputCheckpoint");

            if (dataConnectorRunDto.ProposedCheckpoint != null)
                writer.WriteString("proposedCheckpoint", dataConnectorRunDto.ProposedCheckpoint);
            else
                writer.WriteNull("proposedCheckpoint");

            if (dataConnectorRunDto.ReplayKey != null)
                writer.WriteString("replayKey", dataConnectorRunDto.ReplayKey);
            else
                writer.WriteNull("replayKey");

            if (dataConnectorRunDto.Error != null)
                writer.WriteString("error", dataConnectorRunDto.Error);
            else
                writer.WriteNull("error");
        }
    }
}
