// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// DataConnectorSourceSettingsRequest
    /// </summary>
    public partial class DataConnectorSourceSettingsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataConnectorSourceSettingsRequest" /> class.
        /// </summary>
        /// <param name="sourceTable">sourceTable</param>
        /// <param name="cursorColumn">cursorColumn</param>
        /// <param name="cursorType">cursorType</param>
        /// <param name="pageSize">pageSize (default to 100)</param>
        /// <param name="properties">properties</param>
        /// <param name="cursorIsCommitMonotonic">cursorIsCommitMonotonic (default to false)</param>
        [JsonConstructor]
        public DataConnectorSourceSettingsRequest(Option<string?> sourceTable = default, Option<string?> cursorColumn = default, Option<string?> cursorType = default, Option<int?> pageSize = default, Option<List<string>?> properties = default, Option<bool?> cursorIsCommitMonotonic = default)
        {
            SourceTableOption = sourceTable;
            CursorColumnOption = cursorColumn;
            CursorTypeOption = cursorType;
            PageSizeOption = pageSize;
            PropertiesOption = properties;
            CursorIsCommitMonotonicOption = cursorIsCommitMonotonic;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SourceTable
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceTableOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceTable
        /// </summary>
        [JsonPropertyName("sourceTable")]
        public string? SourceTable { get { return this.SourceTableOption; } set { this.SourceTableOption = new(value); } }

        /// <summary>
        /// Used to track the state of CursorColumn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CursorColumnOption { get; private set; }

        /// <summary>
        /// Gets or Sets CursorColumn
        /// </summary>
        [JsonPropertyName("cursorColumn")]
        public string? CursorColumn { get { return this.CursorColumnOption; } set { this.CursorColumnOption = new(value); } }

        /// <summary>
        /// Used to track the state of CursorType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CursorTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CursorType
        /// </summary>
        [JsonPropertyName("cursorType")]
        public string? CursorType { get { return this.CursorTypeOption; } set { this.CursorTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of PageSize
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PageSizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [JsonPropertyName("pageSize")]
        public int? PageSize { get { return this.PageSizeOption; } set { this.PageSizeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Properties
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> PropertiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [JsonPropertyName("properties")]
        public List<string>? Properties { get { return this.PropertiesOption; } set { this.PropertiesOption = new(value); } }

        /// <summary>
        /// Used to track the state of CursorIsCommitMonotonic
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> CursorIsCommitMonotonicOption { get; private set; }

        /// <summary>
        /// Gets or Sets CursorIsCommitMonotonic
        /// </summary>
        [JsonPropertyName("cursorIsCommitMonotonic")]
        public bool? CursorIsCommitMonotonic { get { return this.CursorIsCommitMonotonicOption; } set { this.CursorIsCommitMonotonicOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataConnectorSourceSettingsRequest {\n");
            sb.Append("  SourceTable: ").Append(SourceTable).Append("\n");
            sb.Append("  CursorColumn: ").Append(CursorColumn).Append("\n");
            sb.Append("  CursorType: ").Append(CursorType).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  CursorIsCommitMonotonic: ").Append(CursorIsCommitMonotonic).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DataConnectorSourceSettingsRequest" />
    /// </summary>
    public class DataConnectorSourceSettingsRequestJsonConverter : JsonConverter<DataConnectorSourceSettingsRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="DataConnectorSourceSettingsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DataConnectorSourceSettingsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sourceTable = default;
            Option<string?> cursorColumn = default;
            Option<string?> cursorType = default;
            Option<int?> pageSize = default;
            Option<List<string>?> properties = default;
            Option<bool?> cursorIsCommitMonotonic = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sourceTable":
                            sourceTable = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cursorColumn":
                            cursorColumn = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cursorType":
                            cursorType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "pageSize":
                            pageSize = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "properties":
                            properties = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "cursorIsCommitMonotonic":
                            cursorIsCommitMonotonic = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (pageSize.IsSet && pageSize.Value == null)
                throw new ArgumentNullException(nameof(pageSize), "Property is not nullable for class DataConnectorSourceSettingsRequest.");

            if (cursorIsCommitMonotonic.IsSet && cursorIsCommitMonotonic.Value == null)
                throw new ArgumentNullException(nameof(cursorIsCommitMonotonic), "Property is not nullable for class DataConnectorSourceSettingsRequest.");

            return new DataConnectorSourceSettingsRequest(sourceTable, cursorColumn, cursorType, pageSize, properties, cursorIsCommitMonotonic);
        }

        /// <summary>
        /// Serializes a <see cref="DataConnectorSourceSettingsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataConnectorSourceSettingsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, DataConnectorSourceSettingsRequest dataConnectorSourceSettingsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dataConnectorSourceSettingsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DataConnectorSourceSettingsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dataConnectorSourceSettingsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, DataConnectorSourceSettingsRequest dataConnectorSourceSettingsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dataConnectorSourceSettingsRequest.SourceTableOption.IsSet)
                if (dataConnectorSourceSettingsRequest.SourceTableOption.Value != null)
                    writer.WriteString("sourceTable", dataConnectorSourceSettingsRequest.SourceTable);
                else
                    writer.WriteNull("sourceTable");

            if (dataConnectorSourceSettingsRequest.CursorColumnOption.IsSet)
                if (dataConnectorSourceSettingsRequest.CursorColumnOption.Value != null)
                    writer.WriteString("cursorColumn", dataConnectorSourceSettingsRequest.CursorColumn);
                else
                    writer.WriteNull("cursorColumn");

            if (dataConnectorSourceSettingsRequest.CursorTypeOption.IsSet)
                if (dataConnectorSourceSettingsRequest.CursorTypeOption.Value != null)
                    writer.WriteString("cursorType", dataConnectorSourceSettingsRequest.CursorType);
                else
                    writer.WriteNull("cursorType");

            if (dataConnectorSourceSettingsRequest.PageSizeOption.IsSet)
                writer.WriteNumber("pageSize", dataConnectorSourceSettingsRequest.PageSizeOption.Value!.Value);

            if (dataConnectorSourceSettingsRequest.PropertiesOption.IsSet)
                if (dataConnectorSourceSettingsRequest.PropertiesOption.Value != null)
                {
                    writer.WritePropertyName("properties");
                    JsonSerializer.Serialize(writer, dataConnectorSourceSettingsRequest.Properties, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("properties");
            if (dataConnectorSourceSettingsRequest.CursorIsCommitMonotonicOption.IsSet)
                writer.WriteBoolean("cursorIsCommitMonotonic", dataConnectorSourceSettingsRequest.CursorIsCommitMonotonicOption.Value!.Value);
        }
    }
}
