// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// QueryResponse
    /// </summary>
    public partial class QueryResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryResponse" /> class.
        /// </summary>
        /// <param name="columns">columns</param>
        /// <param name="rows">rows</param>
        /// <param name="truncated">truncated</param>
        /// <param name="elapsedMilliseconds">elapsedMilliseconds</param>
        /// <param name="language">language</param>
        /// <param name="diagnostics">diagnostics</param>
        /// <param name="rowsAffected">rowsAffected</param>
        /// <param name="generatedSql">generatedSql</param>
        [JsonConstructor]
        public QueryResponse(List<ColumnDto> columns, List<List<Object>> rows, bool truncated, double elapsedMilliseconds, string language, List<QueryDiagnostic> diagnostics, long? rowsAffected = default, string? generatedSql = default)
        {
            Columns = columns;
            Rows = rows;
            Truncated = truncated;
            ElapsedMilliseconds = elapsedMilliseconds;
            Language = language;
            Diagnostics = diagnostics;
            RowsAffected = rowsAffected;
            GeneratedSql = generatedSql;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Columns
        /// </summary>
        [JsonPropertyName("columns")]
        public List<ColumnDto> Columns { get; set; }

        /// <summary>
        /// Gets or Sets Rows
        /// </summary>
        [JsonPropertyName("rows")]
        public List<List<Object>> Rows { get; set; }

        /// <summary>
        /// Gets or Sets Truncated
        /// </summary>
        [JsonPropertyName("truncated")]
        public bool Truncated { get; set; }

        /// <summary>
        /// Gets or Sets ElapsedMilliseconds
        /// </summary>
        [JsonPropertyName("elapsedMilliseconds")]
        public double ElapsedMilliseconds { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [JsonPropertyName("language")]
        public string Language { get; set; }

        /// <summary>
        /// Gets or Sets Diagnostics
        /// </summary>
        [JsonPropertyName("diagnostics")]
        public List<QueryDiagnostic> Diagnostics { get; set; }

        /// <summary>
        /// Gets or Sets RowsAffected
        /// </summary>
        [JsonPropertyName("rowsAffected")]
        public long? RowsAffected { get; set; }

        /// <summary>
        /// Gets or Sets GeneratedSql
        /// </summary>
        [JsonPropertyName("generatedSql")]
        public string? GeneratedSql { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryResponse {\n");
            sb.Append("  Columns: ").Append(Columns).Append("\n");
            sb.Append("  Rows: ").Append(Rows).Append("\n");
            sb.Append("  Truncated: ").Append(Truncated).Append("\n");
            sb.Append("  ElapsedMilliseconds: ").Append(ElapsedMilliseconds).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Diagnostics: ").Append(Diagnostics).Append("\n");
            sb.Append("  RowsAffected: ").Append(RowsAffected).Append("\n");
            sb.Append("  GeneratedSql: ").Append(GeneratedSql).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueryResponse" />
    /// </summary>
    public class QueryResponseJsonConverter : JsonConverter<QueryResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="QueryResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueryResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<ColumnDto>?> columns = default;
            Option<List<List<Object>>?> rows = default;
            Option<bool?> truncated = default;
            Option<double?> elapsedMilliseconds = default;
            Option<string?> language = default;
            Option<List<QueryDiagnostic>?> diagnostics = default;
            Option<long?> rowsAffected = default;
            Option<string?> generatedSql = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "columns":
                            columns = new Option<List<ColumnDto>?>(JsonSerializer.Deserialize<List<ColumnDto>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "rows":
                            rows = new Option<List<List<Object>>?>(JsonSerializer.Deserialize<List<List<Object>>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "truncated":
                            truncated = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "elapsedMilliseconds":
                            elapsedMilliseconds = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "language":
                            language = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "diagnostics":
                            diagnostics = new Option<List<QueryDiagnostic>?>(JsonSerializer.Deserialize<List<QueryDiagnostic>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "rowsAffected":
                            rowsAffected = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "generatedSql":
                            generatedSql = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!columns.IsSet)
                throw new ArgumentException("Property is required for class QueryResponse.", nameof(columns));

            if (!rows.IsSet)
                throw new ArgumentException("Property is required for class QueryResponse.", nameof(rows));

            if (!truncated.IsSet)
                throw new ArgumentException("Property is required for class QueryResponse.", nameof(truncated));

            if (!elapsedMilliseconds.IsSet)
                throw new ArgumentException("Property is required for class QueryResponse.", nameof(elapsedMilliseconds));

            if (!language.IsSet)
                throw new ArgumentException("Property is required for class QueryResponse.", nameof(language));

            if (!diagnostics.IsSet)
                throw new ArgumentException("Property is required for class QueryResponse.", nameof(diagnostics));

            if (!rowsAffected.IsSet)
                throw new ArgumentException("Property is required for class QueryResponse.", nameof(rowsAffected));

            if (!generatedSql.IsSet)
                throw new ArgumentException("Property is required for class QueryResponse.", nameof(generatedSql));

            if (columns.IsSet && columns.Value == null)
                throw new ArgumentNullException(nameof(columns), "Property is not nullable for class QueryResponse.");

            if (rows.IsSet && rows.Value == null)
                throw new ArgumentNullException(nameof(rows), "Property is not nullable for class QueryResponse.");

            if (truncated.IsSet && truncated.Value == null)
                throw new ArgumentNullException(nameof(truncated), "Property is not nullable for class QueryResponse.");

            if (elapsedMilliseconds.IsSet && elapsedMilliseconds.Value == null)
                throw new ArgumentNullException(nameof(elapsedMilliseconds), "Property is not nullable for class QueryResponse.");

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class QueryResponse.");

            if (diagnostics.IsSet && diagnostics.Value == null)
                throw new ArgumentNullException(nameof(diagnostics), "Property is not nullable for class QueryResponse.");

            return new QueryResponse(columns.Value!, rows.Value!, truncated.Value!.Value!, elapsedMilliseconds.Value!.Value!, language.Value!, diagnostics.Value!, rowsAffected.Value!, generatedSql.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="QueryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, QueryResponse queryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queryResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, QueryResponse queryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (queryResponse.Columns == null)
                throw new ArgumentNullException(nameof(queryResponse.Columns), "Property is required for class QueryResponse.");

            if (queryResponse.Rows == null)
                throw new ArgumentNullException(nameof(queryResponse.Rows), "Property is required for class QueryResponse.");

            if (queryResponse.Language == null)
                throw new ArgumentNullException(nameof(queryResponse.Language), "Property is required for class QueryResponse.");

            if (queryResponse.Diagnostics == null)
                throw new ArgumentNullException(nameof(queryResponse.Diagnostics), "Property is required for class QueryResponse.");

            writer.WritePropertyName("columns");
            JsonSerializer.Serialize(writer, queryResponse.Columns, jsonSerializerOptions);
            writer.WritePropertyName("rows");
            JsonSerializer.Serialize(writer, queryResponse.Rows, jsonSerializerOptions);
            writer.WriteBoolean("truncated", queryResponse.Truncated);

            writer.WriteNumber("elapsedMilliseconds", queryResponse.ElapsedMilliseconds);

            writer.WriteString("language", queryResponse.Language);

            writer.WritePropertyName("diagnostics");
            JsonSerializer.Serialize(writer, queryResponse.Diagnostics, jsonSerializerOptions);
            if (queryResponse.RowsAffected != null)
                writer.WriteNumber("rowsAffected", queryResponse.RowsAffected.Value);
            else
                writer.WriteNull("rowsAffected");

            if (queryResponse.GeneratedSql != null)
                writer.WriteString("generatedSql", queryResponse.GeneratedSql);
            else
                writer.WriteNull("generatedSql");
        }
    }
}
