// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// SystemSettingsDto
    /// </summary>
    public partial class SystemSettingsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemSettingsDto" /> class.
        /// </summary>
        /// <param name="mcpEnabled">mcpEnabled</param>
        /// <param name="mcpAllowWrites">mcpAllowWrites</param>
        /// <param name="mcpMaxRowsPerResult">mcpMaxRowsPerResult</param>
        /// <param name="mcpPublicBaseUrl">mcpPublicBaseUrl</param>
        /// <param name="mcpRoute">mcpRoute</param>
        /// <param name="varVersion">varVersion</param>
        /// <param name="updatedUtc">updatedUtc</param>
        [JsonConstructor]
        public SystemSettingsDto(bool mcpEnabled, bool mcpAllowWrites, int mcpMaxRowsPerResult, string mcpPublicBaseUrl, string mcpRoute, int varVersion, DateTime? updatedUtc = default)
        {
            McpEnabled = mcpEnabled;
            McpAllowWrites = mcpAllowWrites;
            McpMaxRowsPerResult = mcpMaxRowsPerResult;
            McpPublicBaseUrl = mcpPublicBaseUrl;
            McpRoute = mcpRoute;
            VarVersion = varVersion;
            UpdatedUtc = updatedUtc;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets McpEnabled
        /// </summary>
        [JsonPropertyName("mcpEnabled")]
        public bool McpEnabled { get; set; }

        /// <summary>
        /// Gets or Sets McpAllowWrites
        /// </summary>
        [JsonPropertyName("mcpAllowWrites")]
        public bool McpAllowWrites { get; set; }

        /// <summary>
        /// Gets or Sets McpMaxRowsPerResult
        /// </summary>
        [JsonPropertyName("mcpMaxRowsPerResult")]
        public int McpMaxRowsPerResult { get; set; }

        /// <summary>
        /// Gets or Sets McpPublicBaseUrl
        /// </summary>
        [JsonPropertyName("mcpPublicBaseUrl")]
        public string McpPublicBaseUrl { get; set; }

        /// <summary>
        /// Gets or Sets McpRoute
        /// </summary>
        [JsonPropertyName("mcpRoute")]
        public string McpRoute { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [JsonPropertyName("version")]
        public int VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedUtc
        /// </summary>
        [JsonPropertyName("updatedUtc")]
        public DateTime? UpdatedUtc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SystemSettingsDto {\n");
            sb.Append("  McpEnabled: ").Append(McpEnabled).Append("\n");
            sb.Append("  McpAllowWrites: ").Append(McpAllowWrites).Append("\n");
            sb.Append("  McpMaxRowsPerResult: ").Append(McpMaxRowsPerResult).Append("\n");
            sb.Append("  McpPublicBaseUrl: ").Append(McpPublicBaseUrl).Append("\n");
            sb.Append("  McpRoute: ").Append(McpRoute).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  UpdatedUtc: ").Append(UpdatedUtc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SystemSettingsDto" />
    /// </summary>
    public class SystemSettingsDtoJsonConverter : JsonConverter<SystemSettingsDto>
    {
        /// <summary>
        /// The format to use to serialize UpdatedUtc
        /// </summary>
        public static string UpdatedUtcFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="SystemSettingsDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SystemSettingsDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> mcpEnabled = default;
            Option<bool?> mcpAllowWrites = default;
            Option<int?> mcpMaxRowsPerResult = default;
            Option<string?> mcpPublicBaseUrl = default;
            Option<string?> mcpRoute = default;
            Option<int?> varVersion = default;
            Option<DateTime?> updatedUtc = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "mcpEnabled":
                            mcpEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "mcpAllowWrites":
                            mcpAllowWrites = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "mcpMaxRowsPerResult":
                            mcpMaxRowsPerResult = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "mcpPublicBaseUrl":
                            mcpPublicBaseUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mcpRoute":
                            mcpRoute = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "version":
                            varVersion = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "updatedUtc":
                            updatedUtc = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!mcpEnabled.IsSet)
                throw new ArgumentException("Property is required for class SystemSettingsDto.", nameof(mcpEnabled));

            if (!mcpAllowWrites.IsSet)
                throw new ArgumentException("Property is required for class SystemSettingsDto.", nameof(mcpAllowWrites));

            if (!mcpMaxRowsPerResult.IsSet)
                throw new ArgumentException("Property is required for class SystemSettingsDto.", nameof(mcpMaxRowsPerResult));

            if (!mcpPublicBaseUrl.IsSet)
                throw new ArgumentException("Property is required for class SystemSettingsDto.", nameof(mcpPublicBaseUrl));

            if (!mcpRoute.IsSet)
                throw new ArgumentException("Property is required for class SystemSettingsDto.", nameof(mcpRoute));

            if (!varVersion.IsSet)
                throw new ArgumentException("Property is required for class SystemSettingsDto.", nameof(varVersion));

            if (!updatedUtc.IsSet)
                throw new ArgumentException("Property is required for class SystemSettingsDto.", nameof(updatedUtc));

            if (mcpEnabled.IsSet && mcpEnabled.Value == null)
                throw new ArgumentNullException(nameof(mcpEnabled), "Property is not nullable for class SystemSettingsDto.");

            if (mcpAllowWrites.IsSet && mcpAllowWrites.Value == null)
                throw new ArgumentNullException(nameof(mcpAllowWrites), "Property is not nullable for class SystemSettingsDto.");

            if (mcpMaxRowsPerResult.IsSet && mcpMaxRowsPerResult.Value == null)
                throw new ArgumentNullException(nameof(mcpMaxRowsPerResult), "Property is not nullable for class SystemSettingsDto.");

            if (mcpPublicBaseUrl.IsSet && mcpPublicBaseUrl.Value == null)
                throw new ArgumentNullException(nameof(mcpPublicBaseUrl), "Property is not nullable for class SystemSettingsDto.");

            if (mcpRoute.IsSet && mcpRoute.Value == null)
                throw new ArgumentNullException(nameof(mcpRoute), "Property is not nullable for class SystemSettingsDto.");

            if (varVersion.IsSet && varVersion.Value == null)
                throw new ArgumentNullException(nameof(varVersion), "Property is not nullable for class SystemSettingsDto.");

            return new SystemSettingsDto(mcpEnabled.Value!.Value!, mcpAllowWrites.Value!.Value!, mcpMaxRowsPerResult.Value!.Value!, mcpPublicBaseUrl.Value!, mcpRoute.Value!, varVersion.Value!.Value!, updatedUtc.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SystemSettingsDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="systemSettingsDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, SystemSettingsDto systemSettingsDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, systemSettingsDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SystemSettingsDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="systemSettingsDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, SystemSettingsDto systemSettingsDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (systemSettingsDto.McpPublicBaseUrl == null)
                throw new ArgumentNullException(nameof(systemSettingsDto.McpPublicBaseUrl), "Property is required for class SystemSettingsDto.");

            if (systemSettingsDto.McpRoute == null)
                throw new ArgumentNullException(nameof(systemSettingsDto.McpRoute), "Property is required for class SystemSettingsDto.");

            writer.WriteBoolean("mcpEnabled", systemSettingsDto.McpEnabled);

            writer.WriteBoolean("mcpAllowWrites", systemSettingsDto.McpAllowWrites);

            writer.WriteNumber("mcpMaxRowsPerResult", systemSettingsDto.McpMaxRowsPerResult);

            writer.WriteString("mcpPublicBaseUrl", systemSettingsDto.McpPublicBaseUrl);

            writer.WriteString("mcpRoute", systemSettingsDto.McpRoute);

            writer.WriteNumber("version", systemSettingsDto.VarVersion);

            if (systemSettingsDto.UpdatedUtc != null)
                writer.WriteString("updatedUtc", systemSettingsDto.UpdatedUtc.Value.ToString(UpdatedUtcFormat));
            else
                writer.WriteNull("updatedUtc");
        }
    }
}
