// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// TableStorageDto
    /// </summary>
    public partial class TableStorageDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableStorageDto" /> class.
        /// </summary>
        /// <param name="schemaName">schemaName</param>
        /// <param name="tableName">tableName</param>
        /// <param name="rowCount">rowCount</param>
        /// <param name="inlinedRows">inlinedRows</param>
        /// <param name="fileCount">fileCount</param>
        /// <param name="fileSizeBytes">fileSizeBytes</param>
        /// <param name="deleteFileCount">deleteFileCount</param>
        /// <param name="deleteFileSizeBytes">deleteFileSizeBytes</param>
        /// <param name="needsFlush">needsFlush</param>
        /// <param name="needsCompaction">needsCompaction</param>
        /// <param name="averageFileSizeBytes">averageFileSizeBytes</param>
        [JsonConstructor]
        public TableStorageDto(string schemaName, string tableName, long rowCount, long inlinedRows, long fileCount, long fileSizeBytes, long deleteFileCount, long deleteFileSizeBytes, bool needsFlush, bool needsCompaction, long? averageFileSizeBytes = default)
        {
            SchemaName = schemaName;
            TableName = tableName;
            RowCount = rowCount;
            InlinedRows = inlinedRows;
            FileCount = fileCount;
            FileSizeBytes = fileSizeBytes;
            DeleteFileCount = deleteFileCount;
            DeleteFileSizeBytes = deleteFileSizeBytes;
            NeedsFlush = needsFlush;
            NeedsCompaction = needsCompaction;
            AverageFileSizeBytes = averageFileSizeBytes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SchemaName
        /// </summary>
        [JsonPropertyName("schemaName")]
        public string SchemaName { get; set; }

        /// <summary>
        /// Gets or Sets TableName
        /// </summary>
        [JsonPropertyName("tableName")]
        public string TableName { get; set; }

        /// <summary>
        /// Gets or Sets RowCount
        /// </summary>
        [JsonPropertyName("rowCount")]
        public long RowCount { get; set; }

        /// <summary>
        /// Gets or Sets InlinedRows
        /// </summary>
        [JsonPropertyName("inlinedRows")]
        public long InlinedRows { get; set; }

        /// <summary>
        /// Gets or Sets FileCount
        /// </summary>
        [JsonPropertyName("fileCount")]
        public long FileCount { get; set; }

        /// <summary>
        /// Gets or Sets FileSizeBytes
        /// </summary>
        [JsonPropertyName("fileSizeBytes")]
        public long FileSizeBytes { get; set; }

        /// <summary>
        /// Gets or Sets DeleteFileCount
        /// </summary>
        [JsonPropertyName("deleteFileCount")]
        public long DeleteFileCount { get; set; }

        /// <summary>
        /// Gets or Sets DeleteFileSizeBytes
        /// </summary>
        [JsonPropertyName("deleteFileSizeBytes")]
        public long DeleteFileSizeBytes { get; set; }

        /// <summary>
        /// Gets or Sets NeedsFlush
        /// </summary>
        [JsonPropertyName("needsFlush")]
        public bool NeedsFlush { get; set; }

        /// <summary>
        /// Gets or Sets NeedsCompaction
        /// </summary>
        [JsonPropertyName("needsCompaction")]
        public bool NeedsCompaction { get; set; }

        /// <summary>
        /// Gets or Sets AverageFileSizeBytes
        /// </summary>
        [JsonPropertyName("averageFileSizeBytes")]
        public long? AverageFileSizeBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TableStorageDto {\n");
            sb.Append("  SchemaName: ").Append(SchemaName).Append("\n");
            sb.Append("  TableName: ").Append(TableName).Append("\n");
            sb.Append("  RowCount: ").Append(RowCount).Append("\n");
            sb.Append("  InlinedRows: ").Append(InlinedRows).Append("\n");
            sb.Append("  FileCount: ").Append(FileCount).Append("\n");
            sb.Append("  FileSizeBytes: ").Append(FileSizeBytes).Append("\n");
            sb.Append("  DeleteFileCount: ").Append(DeleteFileCount).Append("\n");
            sb.Append("  DeleteFileSizeBytes: ").Append(DeleteFileSizeBytes).Append("\n");
            sb.Append("  NeedsFlush: ").Append(NeedsFlush).Append("\n");
            sb.Append("  NeedsCompaction: ").Append(NeedsCompaction).Append("\n");
            sb.Append("  AverageFileSizeBytes: ").Append(AverageFileSizeBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TableStorageDto" />
    /// </summary>
    public class TableStorageDtoJsonConverter : JsonConverter<TableStorageDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="TableStorageDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TableStorageDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> schemaName = default;
            Option<string?> tableName = default;
            Option<long?> rowCount = default;
            Option<long?> inlinedRows = default;
            Option<long?> fileCount = default;
            Option<long?> fileSizeBytes = default;
            Option<long?> deleteFileCount = default;
            Option<long?> deleteFileSizeBytes = default;
            Option<bool?> needsFlush = default;
            Option<bool?> needsCompaction = default;
            Option<long?> averageFileSizeBytes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "schemaName":
                            schemaName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tableName":
                            tableName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "rowCount":
                            rowCount = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "inlinedRows":
                            inlinedRows = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "fileCount":
                            fileCount = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "fileSizeBytes":
                            fileSizeBytes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "deleteFileCount":
                            deleteFileCount = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "deleteFileSizeBytes":
                            deleteFileSizeBytes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "needsFlush":
                            needsFlush = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "needsCompaction":
                            needsCompaction = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "averageFileSizeBytes":
                            averageFileSizeBytes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!schemaName.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(schemaName));

            if (!tableName.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(tableName));

            if (!rowCount.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(rowCount));

            if (!inlinedRows.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(inlinedRows));

            if (!fileCount.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(fileCount));

            if (!fileSizeBytes.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(fileSizeBytes));

            if (!deleteFileCount.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(deleteFileCount));

            if (!deleteFileSizeBytes.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(deleteFileSizeBytes));

            if (!needsFlush.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(needsFlush));

            if (!needsCompaction.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(needsCompaction));

            if (!averageFileSizeBytes.IsSet)
                throw new ArgumentException("Property is required for class TableStorageDto.", nameof(averageFileSizeBytes));

            if (schemaName.IsSet && schemaName.Value == null)
                throw new ArgumentNullException(nameof(schemaName), "Property is not nullable for class TableStorageDto.");

            if (tableName.IsSet && tableName.Value == null)
                throw new ArgumentNullException(nameof(tableName), "Property is not nullable for class TableStorageDto.");

            if (rowCount.IsSet && rowCount.Value == null)
                throw new ArgumentNullException(nameof(rowCount), "Property is not nullable for class TableStorageDto.");

            if (inlinedRows.IsSet && inlinedRows.Value == null)
                throw new ArgumentNullException(nameof(inlinedRows), "Property is not nullable for class TableStorageDto.");

            if (fileCount.IsSet && fileCount.Value == null)
                throw new ArgumentNullException(nameof(fileCount), "Property is not nullable for class TableStorageDto.");

            if (fileSizeBytes.IsSet && fileSizeBytes.Value == null)
                throw new ArgumentNullException(nameof(fileSizeBytes), "Property is not nullable for class TableStorageDto.");

            if (deleteFileCount.IsSet && deleteFileCount.Value == null)
                throw new ArgumentNullException(nameof(deleteFileCount), "Property is not nullable for class TableStorageDto.");

            if (deleteFileSizeBytes.IsSet && deleteFileSizeBytes.Value == null)
                throw new ArgumentNullException(nameof(deleteFileSizeBytes), "Property is not nullable for class TableStorageDto.");

            if (needsFlush.IsSet && needsFlush.Value == null)
                throw new ArgumentNullException(nameof(needsFlush), "Property is not nullable for class TableStorageDto.");

            if (needsCompaction.IsSet && needsCompaction.Value == null)
                throw new ArgumentNullException(nameof(needsCompaction), "Property is not nullable for class TableStorageDto.");

            return new TableStorageDto(schemaName.Value!, tableName.Value!, rowCount.Value!.Value!, inlinedRows.Value!.Value!, fileCount.Value!.Value!, fileSizeBytes.Value!.Value!, deleteFileCount.Value!.Value!, deleteFileSizeBytes.Value!.Value!, needsFlush.Value!.Value!, needsCompaction.Value!.Value!, averageFileSizeBytes.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="TableStorageDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tableStorageDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, TableStorageDto tableStorageDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tableStorageDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TableStorageDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tableStorageDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, TableStorageDto tableStorageDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tableStorageDto.SchemaName == null)
                throw new ArgumentNullException(nameof(tableStorageDto.SchemaName), "Property is required for class TableStorageDto.");

            if (tableStorageDto.TableName == null)
                throw new ArgumentNullException(nameof(tableStorageDto.TableName), "Property is required for class TableStorageDto.");

            writer.WriteString("schemaName", tableStorageDto.SchemaName);

            writer.WriteString("tableName", tableStorageDto.TableName);

            writer.WriteNumber("rowCount", tableStorageDto.RowCount);

            writer.WriteNumber("inlinedRows", tableStorageDto.InlinedRows);

            writer.WriteNumber("fileCount", tableStorageDto.FileCount);

            writer.WriteNumber("fileSizeBytes", tableStorageDto.FileSizeBytes);

            writer.WriteNumber("deleteFileCount", tableStorageDto.DeleteFileCount);

            writer.WriteNumber("deleteFileSizeBytes", tableStorageDto.DeleteFileSizeBytes);

            writer.WriteBoolean("needsFlush", tableStorageDto.NeedsFlush);

            writer.WriteBoolean("needsCompaction", tableStorageDto.NeedsCompaction);

            if (tableStorageDto.AverageFileSizeBytes != null)
                writer.WriteNumber("averageFileSizeBytes", tableStorageDto.AverageFileSizeBytes.Value);
            else
                writer.WriteNull("averageFileSizeBytes");
        }
    }
}
