// <auto-generated>
/*
 * LakeHold Public API
 *
 * Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lakehold.Sdk.Client;

namespace Lakehold.Sdk.Model
{
    /// <summary>
    /// TabularImportDto
    /// </summary>
    public partial class TabularImportDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TabularImportDto" /> class.
        /// </summary>
        /// <param name="fileName">fileName</param>
        /// <param name="format">format</param>
        /// <param name="schema">schema</param>
        /// <param name="table">table</param>
        /// <param name="rowsImported">rowsImported</param>
        /// <param name="rejectedRows">rejectedRows</param>
        /// <param name="recordedErrors">recordedErrors</param>
        /// <param name="rejectsTruncated">rejectsTruncated</param>
        /// <param name="usedAutomaticFallback">usedAutomaticFallback</param>
        /// <param name="columns">columns</param>
        /// <param name="rejects">rejects</param>
        /// <param name="elapsedMilliseconds">elapsedMilliseconds</param>
        [JsonConstructor]
        public TabularImportDto(string fileName, string format, string schema, string table, long rowsImported, long rejectedRows, long recordedErrors, bool rejectsTruncated, bool usedAutomaticFallback, List<TabularImportedColumnDto> columns, List<CsvRejectDto> rejects, double elapsedMilliseconds)
        {
            FileName = fileName;
            Format = format;
            Schema = schema;
            Table = table;
            RowsImported = rowsImported;
            RejectedRows = rejectedRows;
            RecordedErrors = recordedErrors;
            RejectsTruncated = rejectsTruncated;
            UsedAutomaticFallback = usedAutomaticFallback;
            Columns = columns;
            Rejects = rejects;
            ElapsedMilliseconds = elapsedMilliseconds;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets FileName
        /// </summary>
        [JsonPropertyName("fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [JsonPropertyName("format")]
        public string Format { get; set; }

        /// <summary>
        /// Gets or Sets Schema
        /// </summary>
        [JsonPropertyName("schema")]
        public string Schema { get; set; }

        /// <summary>
        /// Gets or Sets Table
        /// </summary>
        [JsonPropertyName("table")]
        public string Table { get; set; }

        /// <summary>
        /// Gets or Sets RowsImported
        /// </summary>
        [JsonPropertyName("rowsImported")]
        public long RowsImported { get; set; }

        /// <summary>
        /// Gets or Sets RejectedRows
        /// </summary>
        [JsonPropertyName("rejectedRows")]
        public long RejectedRows { get; set; }

        /// <summary>
        /// Gets or Sets RecordedErrors
        /// </summary>
        [JsonPropertyName("recordedErrors")]
        public long RecordedErrors { get; set; }

        /// <summary>
        /// Gets or Sets RejectsTruncated
        /// </summary>
        [JsonPropertyName("rejectsTruncated")]
        public bool RejectsTruncated { get; set; }

        /// <summary>
        /// Gets or Sets UsedAutomaticFallback
        /// </summary>
        [JsonPropertyName("usedAutomaticFallback")]
        public bool UsedAutomaticFallback { get; set; }

        /// <summary>
        /// Gets or Sets Columns
        /// </summary>
        [JsonPropertyName("columns")]
        public List<TabularImportedColumnDto> Columns { get; set; }

        /// <summary>
        /// Gets or Sets Rejects
        /// </summary>
        [JsonPropertyName("rejects")]
        public List<CsvRejectDto> Rejects { get; set; }

        /// <summary>
        /// Gets or Sets ElapsedMilliseconds
        /// </summary>
        [JsonPropertyName("elapsedMilliseconds")]
        public double ElapsedMilliseconds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TabularImportDto {\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("  Table: ").Append(Table).Append("\n");
            sb.Append("  RowsImported: ").Append(RowsImported).Append("\n");
            sb.Append("  RejectedRows: ").Append(RejectedRows).Append("\n");
            sb.Append("  RecordedErrors: ").Append(RecordedErrors).Append("\n");
            sb.Append("  RejectsTruncated: ").Append(RejectsTruncated).Append("\n");
            sb.Append("  UsedAutomaticFallback: ").Append(UsedAutomaticFallback).Append("\n");
            sb.Append("  Columns: ").Append(Columns).Append("\n");
            sb.Append("  Rejects: ").Append(Rejects).Append("\n");
            sb.Append("  ElapsedMilliseconds: ").Append(ElapsedMilliseconds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TabularImportDto" />
    /// </summary>
    public class TabularImportDtoJsonConverter : JsonConverter<TabularImportDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="TabularImportDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TabularImportDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> fileName = default;
            Option<string?> format = default;
            Option<string?> schema = default;
            Option<string?> table = default;
            Option<long?> rowsImported = default;
            Option<long?> rejectedRows = default;
            Option<long?> recordedErrors = default;
            Option<bool?> rejectsTruncated = default;
            Option<bool?> usedAutomaticFallback = default;
            Option<List<TabularImportedColumnDto>?> columns = default;
            Option<List<CsvRejectDto>?> rejects = default;
            Option<double?> elapsedMilliseconds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "fileName":
                            fileName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "format":
                            format = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schema":
                            schema = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "table":
                            table = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "rowsImported":
                            rowsImported = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "rejectedRows":
                            rejectedRows = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "recordedErrors":
                            recordedErrors = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "rejectsTruncated":
                            rejectsTruncated = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "usedAutomaticFallback":
                            usedAutomaticFallback = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "columns":
                            columns = new Option<List<TabularImportedColumnDto>?>(JsonSerializer.Deserialize<List<TabularImportedColumnDto>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "rejects":
                            rejects = new Option<List<CsvRejectDto>?>(JsonSerializer.Deserialize<List<CsvRejectDto>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "elapsedMilliseconds":
                            elapsedMilliseconds = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!fileName.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(fileName));

            if (!format.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(format));

            if (!schema.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(schema));

            if (!table.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(table));

            if (!rowsImported.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(rowsImported));

            if (!rejectedRows.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(rejectedRows));

            if (!recordedErrors.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(recordedErrors));

            if (!rejectsTruncated.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(rejectsTruncated));

            if (!usedAutomaticFallback.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(usedAutomaticFallback));

            if (!columns.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(columns));

            if (!rejects.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(rejects));

            if (!elapsedMilliseconds.IsSet)
                throw new ArgumentException("Property is required for class TabularImportDto.", nameof(elapsedMilliseconds));

            if (fileName.IsSet && fileName.Value == null)
                throw new ArgumentNullException(nameof(fileName), "Property is not nullable for class TabularImportDto.");

            if (format.IsSet && format.Value == null)
                throw new ArgumentNullException(nameof(format), "Property is not nullable for class TabularImportDto.");

            if (schema.IsSet && schema.Value == null)
                throw new ArgumentNullException(nameof(schema), "Property is not nullable for class TabularImportDto.");

            if (table.IsSet && table.Value == null)
                throw new ArgumentNullException(nameof(table), "Property is not nullable for class TabularImportDto.");

            if (rowsImported.IsSet && rowsImported.Value == null)
                throw new ArgumentNullException(nameof(rowsImported), "Property is not nullable for class TabularImportDto.");

            if (rejectedRows.IsSet && rejectedRows.Value == null)
                throw new ArgumentNullException(nameof(rejectedRows), "Property is not nullable for class TabularImportDto.");

            if (recordedErrors.IsSet && recordedErrors.Value == null)
                throw new ArgumentNullException(nameof(recordedErrors), "Property is not nullable for class TabularImportDto.");

            if (rejectsTruncated.IsSet && rejectsTruncated.Value == null)
                throw new ArgumentNullException(nameof(rejectsTruncated), "Property is not nullable for class TabularImportDto.");

            if (usedAutomaticFallback.IsSet && usedAutomaticFallback.Value == null)
                throw new ArgumentNullException(nameof(usedAutomaticFallback), "Property is not nullable for class TabularImportDto.");

            if (columns.IsSet && columns.Value == null)
                throw new ArgumentNullException(nameof(columns), "Property is not nullable for class TabularImportDto.");

            if (rejects.IsSet && rejects.Value == null)
                throw new ArgumentNullException(nameof(rejects), "Property is not nullable for class TabularImportDto.");

            if (elapsedMilliseconds.IsSet && elapsedMilliseconds.Value == null)
                throw new ArgumentNullException(nameof(elapsedMilliseconds), "Property is not nullable for class TabularImportDto.");

            return new TabularImportDto(fileName.Value!, format.Value!, schema.Value!, table.Value!, rowsImported.Value!.Value!, rejectedRows.Value!.Value!, recordedErrors.Value!.Value!, rejectsTruncated.Value!.Value!, usedAutomaticFallback.Value!.Value!, columns.Value!, rejects.Value!, elapsedMilliseconds.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="TabularImportDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tabularImportDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, TabularImportDto tabularImportDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tabularImportDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TabularImportDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tabularImportDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, TabularImportDto tabularImportDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tabularImportDto.FileName == null)
                throw new ArgumentNullException(nameof(tabularImportDto.FileName), "Property is required for class TabularImportDto.");

            if (tabularImportDto.Format == null)
                throw new ArgumentNullException(nameof(tabularImportDto.Format), "Property is required for class TabularImportDto.");

            if (tabularImportDto.Schema == null)
                throw new ArgumentNullException(nameof(tabularImportDto.Schema), "Property is required for class TabularImportDto.");

            if (tabularImportDto.Table == null)
                throw new ArgumentNullException(nameof(tabularImportDto.Table), "Property is required for class TabularImportDto.");

            if (tabularImportDto.Columns == null)
                throw new ArgumentNullException(nameof(tabularImportDto.Columns), "Property is required for class TabularImportDto.");

            if (tabularImportDto.Rejects == null)
                throw new ArgumentNullException(nameof(tabularImportDto.Rejects), "Property is required for class TabularImportDto.");

            writer.WriteString("fileName", tabularImportDto.FileName);

            writer.WriteString("format", tabularImportDto.Format);

            writer.WriteString("schema", tabularImportDto.Schema);

            writer.WriteString("table", tabularImportDto.Table);

            writer.WriteNumber("rowsImported", tabularImportDto.RowsImported);

            writer.WriteNumber("rejectedRows", tabularImportDto.RejectedRows);

            writer.WriteNumber("recordedErrors", tabularImportDto.RecordedErrors);

            writer.WriteBoolean("rejectsTruncated", tabularImportDto.RejectsTruncated);

            writer.WriteBoolean("usedAutomaticFallback", tabularImportDto.UsedAutomaticFallback);

            writer.WritePropertyName("columns");
            JsonSerializer.Serialize(writer, tabularImportDto.Columns, jsonSerializerOptions);
            writer.WritePropertyName("rejects");
            JsonSerializer.Serialize(writer, tabularImportDto.Rejects, jsonSerializerOptions);
            writer.WriteNumber("elapsedMilliseconds", tabularImportDto.ElapsedMilliseconds);
        }
    }
}
