# coding: utf-8

"""
    LakeHold Public API

    Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lakehold_sdk.models.data_connector_authentication_request import DataConnectorAuthenticationRequest
from lakehold_sdk.models.data_connector_field_mapping_request import DataConnectorFieldMappingRequest
from lakehold_sdk.models.data_connector_source_settings_request import DataConnectorSourceSettingsRequest
from typing import Optional, Set
from typing_extensions import Self

class DataConnectorDefinitionRequest(BaseModel):
    """
    DataConnectorDefinitionRequest
    """ # noqa: E501
    name: StrictStr
    description: Optional[StrictStr]
    owner: StrictStr
    tags: Optional[List[StrictStr]]
    kind: StrictStr
    endpoint_url: StrictStr = Field(alias="endpointUrl")
    credential_environment_variable: Optional[StrictStr] = Field(alias="credentialEnvironmentVariable")
    rest_response_format: Optional[StrictStr] = Field(alias="restResponseFormat")
    target_schema: StrictStr = Field(alias="targetSchema")
    target_table: StrictStr = Field(alias="targetTable")
    minimum_rows: Optional[StrictInt] = Field(default=1, alias="minimumRows")
    required_columns: Optional[List[StrictStr]] = Field(default=None, alias="requiredColumns")
    not_null_columns: Optional[List[StrictStr]] = Field(default=None, alias="notNullColumns")
    enabled: Optional[StrictBool] = False
    refresh_interval_seconds: Optional[StrictInt] = Field(default=None, alias="refreshIntervalSeconds")
    adapter_id: Optional[StrictStr] = Field(default=None, alias="adapterId")
    adapter_version: Optional[StrictInt] = Field(default=1, alias="adapterVersion")
    read_mode: Optional[StrictStr] = Field(default=None, alias="readMode")
    schema_policy: Optional[StrictStr] = Field(default=None, alias="schemaPolicy")
    key_columns: Optional[List[StrictStr]] = Field(default=None, alias="keyColumns")
    field_mappings: Optional[List[DataConnectorFieldMappingRequest]] = Field(default=None, alias="fieldMappings")
    source_settings: Optional[DataConnectorSourceSettingsRequest] = Field(default=None, alias="sourceSettings")
    authentication: Optional[DataConnectorAuthenticationRequest] = None
    max_attempts: Optional[StrictInt] = Field(default=5, alias="maxAttempts")
    retry_base_seconds: Optional[StrictInt] = Field(default=30, alias="retryBaseSeconds")
    retry_max_seconds: Optional[StrictInt] = Field(default=3600, alias="retryMaxSeconds")
    __properties: ClassVar[List[str]] = ["name", "description", "owner", "tags", "kind", "endpointUrl", "credentialEnvironmentVariable", "restResponseFormat", "targetSchema", "targetTable", "minimumRows", "requiredColumns", "notNullColumns", "enabled", "refreshIntervalSeconds", "adapterId", "adapterVersion", "readMode", "schemaPolicy", "keyColumns", "fieldMappings", "sourceSettings", "authentication", "maxAttempts", "retryBaseSeconds", "retryMaxSeconds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataConnectorDefinitionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in field_mappings (list)
        _items = []
        if self.field_mappings:
            for _item_field_mappings in self.field_mappings:
                if _item_field_mappings:
                    _items.append(_item_field_mappings.to_dict())
            _dict['fieldMappings'] = _items
        # override the default output from pydantic by calling `to_dict()` of source_settings
        if self.source_settings:
            _dict['sourceSettings'] = self.source_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of authentication
        if self.authentication:
            _dict['authentication'] = self.authentication.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if credential_environment_variable (nullable) is None
        # and model_fields_set contains the field
        if self.credential_environment_variable is None and "credential_environment_variable" in self.model_fields_set:
            _dict['credentialEnvironmentVariable'] = None

        # set to None if rest_response_format (nullable) is None
        # and model_fields_set contains the field
        if self.rest_response_format is None and "rest_response_format" in self.model_fields_set:
            _dict['restResponseFormat'] = None

        # set to None if required_columns (nullable) is None
        # and model_fields_set contains the field
        if self.required_columns is None and "required_columns" in self.model_fields_set:
            _dict['requiredColumns'] = None

        # set to None if not_null_columns (nullable) is None
        # and model_fields_set contains the field
        if self.not_null_columns is None and "not_null_columns" in self.model_fields_set:
            _dict['notNullColumns'] = None

        # set to None if refresh_interval_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.refresh_interval_seconds is None and "refresh_interval_seconds" in self.model_fields_set:
            _dict['refreshIntervalSeconds'] = None

        # set to None if adapter_id (nullable) is None
        # and model_fields_set contains the field
        if self.adapter_id is None and "adapter_id" in self.model_fields_set:
            _dict['adapterId'] = None

        # set to None if read_mode (nullable) is None
        # and model_fields_set contains the field
        if self.read_mode is None and "read_mode" in self.model_fields_set:
            _dict['readMode'] = None

        # set to None if schema_policy (nullable) is None
        # and model_fields_set contains the field
        if self.schema_policy is None and "schema_policy" in self.model_fields_set:
            _dict['schemaPolicy'] = None

        # set to None if key_columns (nullable) is None
        # and model_fields_set contains the field
        if self.key_columns is None and "key_columns" in self.model_fields_set:
            _dict['keyColumns'] = None

        # set to None if field_mappings (nullable) is None
        # and model_fields_set contains the field
        if self.field_mappings is None and "field_mappings" in self.model_fields_set:
            _dict['fieldMappings'] = None

        # set to None if source_settings (nullable) is None
        # and model_fields_set contains the field
        if self.source_settings is None and "source_settings" in self.model_fields_set:
            _dict['sourceSettings'] = None

        # set to None if authentication (nullable) is None
        # and model_fields_set contains the field
        if self.authentication is None and "authentication" in self.model_fields_set:
            _dict['authentication'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataConnectorDefinitionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "owner": obj.get("owner"),
            "tags": obj.get("tags"),
            "kind": obj.get("kind"),
            "endpointUrl": obj.get("endpointUrl"),
            "credentialEnvironmentVariable": obj.get("credentialEnvironmentVariable"),
            "restResponseFormat": obj.get("restResponseFormat"),
            "targetSchema": obj.get("targetSchema"),
            "targetTable": obj.get("targetTable"),
            "minimumRows": obj.get("minimumRows") if obj.get("minimumRows") is not None else 1,
            "requiredColumns": obj.get("requiredColumns"),
            "notNullColumns": obj.get("notNullColumns"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else False,
            "refreshIntervalSeconds": obj.get("refreshIntervalSeconds"),
            "adapterId": obj.get("adapterId"),
            "adapterVersion": obj.get("adapterVersion") if obj.get("adapterVersion") is not None else 1,
            "readMode": obj.get("readMode"),
            "schemaPolicy": obj.get("schemaPolicy"),
            "keyColumns": obj.get("keyColumns"),
            "fieldMappings": [DataConnectorFieldMappingRequest.from_dict(_item) for _item in obj["fieldMappings"]] if obj.get("fieldMappings") is not None else None,
            "sourceSettings": DataConnectorSourceSettingsRequest.from_dict(obj["sourceSettings"]) if obj.get("sourceSettings") is not None else None,
            "authentication": DataConnectorAuthenticationRequest.from_dict(obj["authentication"]) if obj.get("authentication") is not None else None,
            "maxAttempts": obj.get("maxAttempts") if obj.get("maxAttempts") is not None else 5,
            "retryBaseSeconds": obj.get("retryBaseSeconds") if obj.get("retryBaseSeconds") is not None else 30,
            "retryMaxSeconds": obj.get("retryMaxSeconds") if obj.get("retryMaxSeconds") is not None else 3600
        })
        return _obj


