# coding: utf-8

"""
    LakeHold Public API

    Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lakehold_sdk.models.data_connector_authentication_dto import DataConnectorAuthenticationDto
from lakehold_sdk.models.data_connector_field_mapping_dto import DataConnectorFieldMappingDto
from lakehold_sdk.models.data_connector_source_settings_dto import DataConnectorSourceSettingsDto
from typing import Optional, Set
from typing_extensions import Self

class DataConnectorDto(BaseModel):
    """
    DataConnectorDto
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    description: Optional[StrictStr]
    owner: StrictStr
    tags: List[StrictStr]
    kind: StrictStr
    adapter_id: StrictStr = Field(alias="adapterId")
    adapter_version: StrictInt = Field(alias="adapterVersion")
    read_mode: StrictStr = Field(alias="readMode")
    endpoint_url: StrictStr = Field(alias="endpointUrl")
    credential_environment_variable: Optional[StrictStr] = Field(alias="credentialEnvironmentVariable")
    rest_response_format: StrictStr = Field(alias="restResponseFormat")
    source_settings: DataConnectorSourceSettingsDto = Field(alias="sourceSettings")
    authentication: DataConnectorAuthenticationDto
    field_mappings: List[DataConnectorFieldMappingDto] = Field(alias="fieldMappings")
    schema_policy: StrictStr = Field(alias="schemaPolicy")
    key_columns: List[StrictStr] = Field(alias="keyColumns")
    checkpoint: Optional[StrictStr]
    checkpoint_version: StrictInt = Field(alias="checkpointVersion")
    target_schema: StrictStr = Field(alias="targetSchema")
    target_table: StrictStr = Field(alias="targetTable")
    minimum_rows: StrictInt = Field(alias="minimumRows")
    required_columns: List[StrictStr] = Field(alias="requiredColumns")
    not_null_columns: List[StrictStr] = Field(alias="notNullColumns")
    enabled: StrictBool
    refresh_interval_seconds: Optional[StrictInt] = Field(alias="refreshIntervalSeconds")
    next_run_utc: Optional[datetime] = Field(alias="nextRunUtc")
    last_completed_utc: Optional[datetime] = Field(alias="lastCompletedUtc")
    last_error: Optional[StrictStr] = Field(alias="lastError")
    source_acknowledgement_pending_utc: Optional[datetime] = Field(default=None, alias="sourceAcknowledgementPendingUtc")
    source_acknowledgement_error: Optional[StrictStr] = Field(default=None, alias="sourceAcknowledgementError")
    consecutive_failures: StrictInt = Field(alias="consecutiveFailures")
    max_attempts: StrictInt = Field(alias="maxAttempts")
    retry_base_seconds: StrictInt = Field(alias="retryBaseSeconds")
    retry_max_seconds: StrictInt = Field(alias="retryMaxSeconds")
    paused_utc: Optional[datetime] = Field(alias="pausedUtc")
    target_provisioned: StrictBool = Field(alias="targetProvisioned")
    archived_utc: Optional[datetime] = Field(alias="archivedUtc")
    version: StrictInt
    created_utc: datetime = Field(alias="createdUtc")
    updated_utc: datetime = Field(alias="updatedUtc")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "owner", "tags", "kind", "adapterId", "adapterVersion", "readMode", "endpointUrl", "credentialEnvironmentVariable", "restResponseFormat", "sourceSettings", "authentication", "fieldMappings", "schemaPolicy", "keyColumns", "checkpoint", "checkpointVersion", "targetSchema", "targetTable", "minimumRows", "requiredColumns", "notNullColumns", "enabled", "refreshIntervalSeconds", "nextRunUtc", "lastCompletedUtc", "lastError", "sourceAcknowledgementPendingUtc", "sourceAcknowledgementError", "consecutiveFailures", "maxAttempts", "retryBaseSeconds", "retryMaxSeconds", "pausedUtc", "targetProvisioned", "archivedUtc", "version", "createdUtc", "updatedUtc"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataConnectorDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source_settings
        if self.source_settings:
            _dict['sourceSettings'] = self.source_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of authentication
        if self.authentication:
            _dict['authentication'] = self.authentication.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in field_mappings (list)
        _items = []
        if self.field_mappings:
            for _item_field_mappings in self.field_mappings:
                if _item_field_mappings:
                    _items.append(_item_field_mappings.to_dict())
            _dict['fieldMappings'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if credential_environment_variable (nullable) is None
        # and model_fields_set contains the field
        if self.credential_environment_variable is None and "credential_environment_variable" in self.model_fields_set:
            _dict['credentialEnvironmentVariable'] = None

        # set to None if checkpoint (nullable) is None
        # and model_fields_set contains the field
        if self.checkpoint is None and "checkpoint" in self.model_fields_set:
            _dict['checkpoint'] = None

        # set to None if refresh_interval_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.refresh_interval_seconds is None and "refresh_interval_seconds" in self.model_fields_set:
            _dict['refreshIntervalSeconds'] = None

        # set to None if next_run_utc (nullable) is None
        # and model_fields_set contains the field
        if self.next_run_utc is None and "next_run_utc" in self.model_fields_set:
            _dict['nextRunUtc'] = None

        # set to None if last_completed_utc (nullable) is None
        # and model_fields_set contains the field
        if self.last_completed_utc is None and "last_completed_utc" in self.model_fields_set:
            _dict['lastCompletedUtc'] = None

        # set to None if last_error (nullable) is None
        # and model_fields_set contains the field
        if self.last_error is None and "last_error" in self.model_fields_set:
            _dict['lastError'] = None

        # set to None if source_acknowledgement_pending_utc (nullable) is None
        # and model_fields_set contains the field
        if self.source_acknowledgement_pending_utc is None and "source_acknowledgement_pending_utc" in self.model_fields_set:
            _dict['sourceAcknowledgementPendingUtc'] = None

        # set to None if source_acknowledgement_error (nullable) is None
        # and model_fields_set contains the field
        if self.source_acknowledgement_error is None and "source_acknowledgement_error" in self.model_fields_set:
            _dict['sourceAcknowledgementError'] = None

        # set to None if paused_utc (nullable) is None
        # and model_fields_set contains the field
        if self.paused_utc is None and "paused_utc" in self.model_fields_set:
            _dict['pausedUtc'] = None

        # set to None if archived_utc (nullable) is None
        # and model_fields_set contains the field
        if self.archived_utc is None and "archived_utc" in self.model_fields_set:
            _dict['archivedUtc'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataConnectorDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "owner": obj.get("owner"),
            "tags": obj.get("tags"),
            "kind": obj.get("kind"),
            "adapterId": obj.get("adapterId"),
            "adapterVersion": obj.get("adapterVersion"),
            "readMode": obj.get("readMode"),
            "endpointUrl": obj.get("endpointUrl"),
            "credentialEnvironmentVariable": obj.get("credentialEnvironmentVariable"),
            "restResponseFormat": obj.get("restResponseFormat"),
            "sourceSettings": DataConnectorSourceSettingsDto.from_dict(obj["sourceSettings"]) if obj.get("sourceSettings") is not None else None,
            "authentication": DataConnectorAuthenticationDto.from_dict(obj["authentication"]) if obj.get("authentication") is not None else None,
            "fieldMappings": [DataConnectorFieldMappingDto.from_dict(_item) for _item in obj["fieldMappings"]] if obj.get("fieldMappings") is not None else None,
            "schemaPolicy": obj.get("schemaPolicy"),
            "keyColumns": obj.get("keyColumns"),
            "checkpoint": obj.get("checkpoint"),
            "checkpointVersion": obj.get("checkpointVersion"),
            "targetSchema": obj.get("targetSchema"),
            "targetTable": obj.get("targetTable"),
            "minimumRows": obj.get("minimumRows"),
            "requiredColumns": obj.get("requiredColumns"),
            "notNullColumns": obj.get("notNullColumns"),
            "enabled": obj.get("enabled"),
            "refreshIntervalSeconds": obj.get("refreshIntervalSeconds"),
            "nextRunUtc": obj.get("nextRunUtc"),
            "lastCompletedUtc": obj.get("lastCompletedUtc"),
            "lastError": obj.get("lastError"),
            "sourceAcknowledgementPendingUtc": obj.get("sourceAcknowledgementPendingUtc"),
            "sourceAcknowledgementError": obj.get("sourceAcknowledgementError"),
            "consecutiveFailures": obj.get("consecutiveFailures"),
            "maxAttempts": obj.get("maxAttempts"),
            "retryBaseSeconds": obj.get("retryBaseSeconds"),
            "retryMaxSeconds": obj.get("retryMaxSeconds"),
            "pausedUtc": obj.get("pausedUtc"),
            "targetProvisioned": obj.get("targetProvisioned"),
            "archivedUtc": obj.get("archivedUtc"),
            "version": obj.get("version"),
            "createdUtc": obj.get("createdUtc"),
            "updatedUtc": obj.get("updatedUtc")
        })
        return _obj


