# coding: utf-8

"""
    LakeHold Public API

    Stable, versioned control-plane and lakehouse API for LakeHold. Send machine credentials as a Bearer token and an Idempotency-Key on retryable mutations.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateSystemSettingsRequest(BaseModel):
    """
    UpdateSystemSettingsRequest
    """ # noqa: E501
    mcp_enabled: StrictBool = Field(alias="mcpEnabled")
    mcp_allow_writes: StrictBool = Field(alias="mcpAllowWrites")
    mcp_max_rows_per_result: StrictInt = Field(alias="mcpMaxRowsPerResult")
    mcp_public_base_url: Optional[StrictStr] = Field(alias="mcpPublicBaseUrl")
    version: StrictInt
    __properties: ClassVar[List[str]] = ["mcpEnabled", "mcpAllowWrites", "mcpMaxRowsPerResult", "mcpPublicBaseUrl", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateSystemSettingsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if mcp_public_base_url (nullable) is None
        # and model_fields_set contains the field
        if self.mcp_public_base_url is None and "mcp_public_base_url" in self.model_fields_set:
            _dict['mcpPublicBaseUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateSystemSettingsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mcpEnabled": obj.get("mcpEnabled"),
            "mcpAllowWrites": obj.get("mcpAllowWrites"),
            "mcpMaxRowsPerResult": obj.get("mcpMaxRowsPerResult"),
            "mcpPublicBaseUrl": obj.get("mcpPublicBaseUrl"),
            "version": obj.get("version")
        })
        return _obj


